// Decompiled code dump generated by CodeDumper

// --------
#PTN v0
// @PTN LEGEND
// Nodes: L(F,i)=local i in function F; P(F,i)=param i of F; G(addr)=global at addr; F(Fx)=function Fx.
// Slices: @[off:len] in bytes; '?' unknown; '&' = address-of; '*' = deref; optional cast as :(type).
// A: alias inside function   => A: dst := src[@slice][mode][:cast] {meta}
// I: inbound (caller→this)   => I: origin -> P(F,i) {caller=F?,cs=0x...,conf=...}
// E: outbound (this→callee)  => E: origin -> A(F?,arg) [-> A(F?,arg)...] {cs=0x...,conf=...}
// G: global touch/summary    => G: F(F?) -> G(0xADDR)   or   G: F(writer) -> G(0xADDR) -> F(reader)
// Dictionary entry (per function block): // @PTN D:F?=0xEA,Name
// --------

// Start Function: 0x14317D700 (SWeaponStats::Init)
// Caller Depth: 0
// Callee/Ref Depth: 5
// Total Functions Found: 17
// Included Functions (17):
//   - sub_140369E60 (0x140369E60)
//   - sub_14037BF20 (0x14037BF20)
//   - sub_14046E5B0 (0x14046E5B0)
//   - sub_14275A5F0 (0x14275A5F0)
//   - SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0)
//   - SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0)
//   - SAimRecoilModifier::Init (0x143175900)
//   - SWeaponStats::Init (0x14317D700)
//   - SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0)
//   - SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0)
//   - SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0)
//   - sub_145FD4610 (0x145FD4610)
//   - SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780)
//   - SRecoilModifier::Init (0x14317BA10)
//   - sub_145FD2960 (0x145FD2960)
//   - SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10)
//   - SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0)
// Removed Functions: None
// ------------------------------------------------------------

// Incoming xrefs for sub_140369E60 (0x140369E60): sub_145FD2960 (0x145FD2960) [direct_call], SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call], SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call], SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for sub_140369E60 (0x140369E60): None
// @PTN D:F1=0x140369E60,sub_140369E60
// @PTN A:U(F1,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F11,0)@[?:0x8] {conf=high,cs=0x145FD2ACE,caller=F11} -> P(F1,0)
// @PTN I:L(F16,0)@[?:0x8] {conf=high,cs=0x145FD578E,caller=F16} -> P(F1,0)
// @PTN I:L(F17,0)@[?:0x8] {conf=high,cs=0x145FD5A1E,caller=F17} -> P(F1,0)
// @PTN I:L(F12,0)@[?:0x8] {conf=high,cs=0x145FD2BDE,caller=F12} -> P(F1,0)
// @PTN I:L(F15,0)@[?:0x8] {conf=high,cs=0x145FD461E,caller=F15} -> P(F1,0)
// @PTN I:L(F10,0)@[?:0x8] {conf=high,cs=0x145FD296E,caller=F10} -> P(F1,0)
// @PTN I:L(F13,0)@[?:0x8] {conf=high,cs=0x145FD2CF4,caller=F13} -> P(F1,0)
// @PTN I:L(F14,0)@[?:0x8] {conf=high,cs=0x145FD45AE,caller=F14} -> P(F1,0)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// --- Function: sub_140369E60 (0x140369E60) ---
_QWORD *__fastcall sub_140369E60(_QWORD *a1)
{
  *a1 = &off_1485D0AA8;
  return a1;
}

// --- End Function: sub_140369E60 (0x140369E60) ---

// Incoming xrefs for sub_14037BF20 (0x14037BF20): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for sub_14037BF20 (0x14037BF20): None
// @PTN D:F2=0x14037BF20,sub_14037BF20
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F13,6)@[?:0x8] {conf=high,cs=0x145FD2E26,caller=F13} -> P(F2,0)
// @PTN I:L(F13,7)@[?:0x8] {conf=high,cs=0x145FD2E51,caller=F13} -> P(F2,0)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// --- Function: sub_14037BF20 (0x14037BF20) ---
void *(__fastcall **__fastcall sub_14037BF20(_QWORD *a1))(RBX::DataModelEmptySerialize *__hidden this, unsigned int)
{
  a1[7] = &off_1485D0AA8;
  a1[4] = &off_1485D0AA8;
  a1[1] = &off_1485D0AA8;
  *a1 = &off_1485D0AA8;
  return &off_1485D0AA8;
}

// --- End Function: sub_14037BF20 (0x14037BF20) ---

// Incoming xrefs for sub_14046E5B0 (0x14046E5B0): sub_145FD2960 (0x145FD2960) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for sub_14046E5B0 (0x14046E5B0): None
// @PTN D:F3=0x14046E5B0,sub_14046E5B0
// @PTN A:U(F3,-1):=G(0x1485EF230)@[?:0x8] {conf=med}
// @PTN I:L(F17,0)@[0x18:0x8] {conf=high,cs=0x145FD5A74,caller=F17} -> P(F3,0)
// @PTN I:L(F17,0)@[0x30:0x8] {conf=high,cs=0x145FD5A85,caller=F17} -> P(F3,0)
// @PTN I:L(F12,0)@[0x8:0x8] {conf=high,cs=0x145FD2BFE,caller=F12} -> P(F3,0)
// @PTN I:L(F12,0)@[0x20:0x8] {conf=high,cs=0x145FD2C0F,caller=F12} -> P(F3,0)
// @PTN I:L(F12,0)@[0x38:0x8] {conf=high,cs=0x145FD2C20,caller=F12} -> P(F3,0)
// @PTN I:L(F15,0)@[0x8:0x8] {conf=high,cs=0x145FD463E,caller=F15} -> P(F3,0)
// @PTN I:L(F15,0)@[0x20:0x8] {conf=high,cs=0x145FD464F,caller=F15} -> P(F3,0)
// @PTN I:L(F10,0)@[0x20:0x8] {conf=high,cs=0x145FD29E8,caller=F10} -> P(F3,0)
// @PTN I:L(F10,0)@[0x38:0x8] {conf=high,cs=0x145FD29F9,caller=F10} -> P(F3,0)
// @PTN G:G(0x1485EF230) -> F(F3)
// @PTN G:G(0x1485EF230) -> F(F3)
// @PTN G:G(0x1485EF230) -> F(F3)
// --- Function: sub_14046E5B0 (0x14046E5B0) ---
_QWORD *__fastcall sub_14046E5B0(_QWORD *a1)
{
  *a1 = &off_1485EF230;
  return a1;
}

// --- End Function: sub_14046E5B0 (0x14046E5B0) ---

// Incoming xrefs for sub_14275A5F0 (0x14275A5F0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for sub_14275A5F0 (0x14275A5F0): None
// @PTN D:F4=0x14275A5F0,sub_14275A5F0
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F13,8)@[?:0x8] {conf=high,cs=0x145FD2DCD,caller=F13} -> P(F4,0)
// @PTN I:L(F13,9)@[?:0x8] {conf=high,cs=0x145FD2DFB,caller=F13} -> P(F4,0)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// --- Function: sub_14275A5F0 (0x14275A5F0) ---
void *(__fastcall **__fastcall sub_14275A5F0(_QWORD *a1))(RBX::DataModelEmptySerialize *__hidden this, unsigned int)
{
  a1[9] = &off_1485D0AA8;
  a1[6] = &off_1485D0AA8;
  a1[3] = &off_1485D0AA8;
  *a1 = &off_1485D0AA8;
  return &off_1485D0AA8;
}

// --- End Function: sub_14275A5F0 (0x14275A5F0) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0): None
// @PTN D:F8=0x143181DF0,SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams
// @PTN I:L(F13,0)@[0xD8:0x8] {conf=high,cs=0x145FD2E1C,caller=F13} -> P(F8,0)
// @PTN I:L(F13,0)@[0x128:0x8] {conf=high,cs=0x145FD2E47,caller=F13} -> P(F8,0)
// @PTN I:L(F13,3)@[?:0x8] {conf=high,cs=0x145FD2E1C,caller=F13} -> P(F8,1)
// @PTN I:L(F13,4)@[?:0x8] {conf=high,cs=0x145FD2E47,caller=F13} -> P(F8,1)
// --- Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) ---
__int64 __fastcall SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams(__int64 a1, __int64 a2)
{
  *(double *)(a1 + 16) = *(double *)(a2 + 16);
  *(_DWORD *)(a1 + 24) = *(_DWORD *)(a2 + 24);
  *(double *)(a1 + 40) = *(double *)(a2 + 40);
  *(_DWORD *)(a1 + 48) = *(_DWORD *)(a2 + 48);
  *(double *)(a1 + 64) = *(double *)(a2 + 64);
  *(_DWORD *)(a1 + 72) = *(_DWORD *)(a2 + 72);
  return a1;
}

// --- End Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) ---

// Incoming xrefs for SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0): None
// @PTN D:F9=0x1431833F0,SXYZCurvesWithMaxValuesModifer::CopyParams
// @PTN I:L(F13,0)@[0x10:0x8] {conf=high,cs=0x145FD2DC0,caller=F13} -> P(F9,0)
// @PTN I:L(F13,0)@[0x70:0x8] {conf=high,cs=0x145FD2DEE,caller=F13} -> P(F9,0)
// @PTN I:L(F13,1)@[?:0x8] {conf=high,cs=0x145FD2DC0,caller=F13} -> P(F9,1)
// @PTN I:L(F13,2)@[?:0x8] {conf=high,cs=0x145FD2DEE,caller=F13} -> P(F9,1)
// --- Function: SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) ---
__int64 __fastcall SXYZCurvesWithMaxValuesModifer::CopyParams(__int64 a1, __int64 a2)
{
  *(_DWORD *)(a1 + 8) = *(_DWORD *)(a2 + 8);
  *(_DWORD *)(a1 + 12) = *(_DWORD *)(a2 + 12);
  *(_DWORD *)(a1 + 16) = *(_DWORD *)(a2 + 16);
  *(double *)(a1 + 32) = *(double *)(a2 + 32);
  *(_DWORD *)(a1 + 40) = *(_DWORD *)(a2 + 40);
  *(double *)(a1 + 56) = *(double *)(a2 + 56);
  *(_DWORD *)(a1 + 64) = *(_DWORD *)(a2 + 64);
  *(_DWORD *)(a1 + 80) = *(_DWORD *)(a2 + 80);
  *(_DWORD *)(a1 + 84) = *(_DWORD *)(a2 + 84);
  *(_DWORD *)(a1 + 88) = *(_DWORD *)(a2 + 88);
  return a1;
}

// --- End Function: SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) ---

// Incoming xrefs for SAimRecoilModifier::Init (0x143175900): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SAimRecoilModifier::Init (0x143175900): sub_145FD2960 (0x145FD2960) [direct_call]
// @PTN D:F5=0x143175900,SAimRecoilModifier::Init
// @PTN A:U(F5,-1):=G(0x148AE9F40)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x58:0x8] {conf=high,cs=0x14317BA8D,caller=F6} -> P(F5,0)
// @PTN E:L(F5,0)@[0x48:0x8]:(char *) {conf=high,cs=0x143175946} -> A(F10,0)
// @PTN G:G(0x148AE9F40) -> F(F5)
// @PTN G:G(0x148AE9F40) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x145FD2960) -> F(F5)
// @PTN G:G(0x145FD2960) -> F(F5)
// --- Function: SAimRecoilModifier::Init (0x143175900) ---
SAimRecoilModifier *__fastcall SAimRecoilModifier::Init(SAimRecoilModifier *p_aimRecoilModifier)
{
  *((_DWORD *)p_aimRecoilModifier + 14) = 1065353216;
  *(_QWORD *)p_aimRecoilModifier = off_148AE9F40;
  *((_DWORD *)p_aimRecoilModifier + 15) = 1065353216;
  *((_QWORD *)p_aimRecoilModifier + 1) = &off_14867BA00;
  *((_QWORD *)p_aimRecoilModifier + 3) = &off_14867BA00;
  *((_QWORD *)p_aimRecoilModifier + 5) = &off_14867BA00;
  *((_DWORD *)p_aimRecoilModifier + 16) = 1065353216;
  *((_DWORD *)p_aimRecoilModifier + 17) = 1065353216;
  sub_145FD2960((char *)p_aimRecoilModifier + 72);
  *((_DWORD *)p_aimRecoilModifier + 4) = 1065353216;
  *((_DWORD *)p_aimRecoilModifier + 5) = 1065353216;
  *((_DWORD *)p_aimRecoilModifier + 8) = 1065353216;
  *((_DWORD *)p_aimRecoilModifier + 9) = 1065353216;
  *((_DWORD *)p_aimRecoilModifier + 12) = 1065353216;
  *((_DWORD *)p_aimRecoilModifier + 13) = 1065353216;
  return p_aimRecoilModifier;
}

// --- End Function: SAimRecoilModifier::Init (0x143175900) ---

// Incoming xrefs for SWeaponStats::Init (0x14317D700): None
// Outgoing xrefs for SWeaponStats::Init (0x14317D700): SRecoilModifier::Init (0x14317BA10) [direct_call]
// @PTN D:F7=0x14317D700,SWeaponStats::Init
// @PTN A:U(F7,-1):=G(0x148AEA0D8)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AE9FC8)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA008)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA048)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA090)@[?:0x8] {conf=med}
// @PTN E:L(F7,0)@[0x38:0x8]:(__int64) {conf=high,cs=0x14317D75D} -> A(F6,0)
// @PTN G:G(0x148AEA0D8) -> F(F7)
// @PTN G:G(0x148AEA0D8) -> F(F7)
// @PTN G:G(0x14317BA10) -> F(F7)
// @PTN G:G(0x14317BA10) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// --- Function: SWeaponStats::Init (0x14317D700) ---
SWeaponStats *__fastcall SWeaponStats::Init(SWeaponStats *SWeaponStats)
{
  *((_DWORD *)SWeaponStats + 3) = 1065353216;
  *((_DWORD *)SWeaponStats + 2) = 0;
  *(_QWORD *)SWeaponStats = off_148AEA0D8;
  *((_QWORD *)SWeaponStats + 4) = 0;
  *((_DWORD *)SWeaponStats + 4) = 1065353216;
  *((_DWORD *)SWeaponStats + 5) = 1065353216;
  *((_QWORD *)SWeaponStats + 3) = 1065353216;
  *((_DWORD *)SWeaponStats + 10) = 1065353216;
  *((_DWORD *)SWeaponStats + 11) = 1065353216;
  *((_DWORD *)SWeaponStats + 12) = 1065353216;
  *((_DWORD *)SWeaponStats + 13) = 1065353216;
  SRecoilModifier::Init((__int64)SWeaponStats + 56);
  *((_DWORD *)SWeaponStats + 214) = 1065353216;
  *((_QWORD *)SWeaponStats + 106) = &off_148AE9FC8;
  *((_QWORD *)SWeaponStats + 110) = &off_148AEA008;
  *((_QWORD *)SWeaponStats + 114) = &off_148AEA048;
  *((_QWORD *)SWeaponStats + 117) = &off_148AEA090;
  *((_DWORD *)SWeaponStats + 215) = 1065353216;
  *((_DWORD *)SWeaponStats + 216) = 1065353216;
  *((_DWORD *)SWeaponStats + 217) = 1065353216;
  *((_QWORD *)SWeaponStats + 109) = 1065353216;
  *((_DWORD *)SWeaponStats + 222) = 1065353216;
  *((_DWORD *)SWeaponStats + 223) = 1065353216;
  *((_DWORD *)SWeaponStats + 224) = 1065353216;
  *((_BYTE *)SWeaponStats + 900) = 0;
  *((_DWORD *)SWeaponStats + 226) = 1065353216;
  *((_DWORD *)SWeaponStats + 230) = 1065353216;
  *((_DWORD *)SWeaponStats + 231) = 1065353216;
  *((_DWORD *)SWeaponStats + 232) = 1065353216;
  *((_DWORD *)SWeaponStats + 236) = 1065353216;
  *((_DWORD *)SWeaponStats + 237) = 1065353216;
  *((_DWORD *)SWeaponStats + 238) = 1065353216;
  *((_WORD *)SWeaponStats + 480) = 0;
  return SWeaponStats;
}

// --- End Function: SWeaponStats::Init (0x14317D700) ---

// Incoming xrefs for SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0): sub_145FD2960 (0x145FD2960) [direct_call]
// Outgoing xrefs for SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0): sub_140369E60 (0x140369E60) [direct_call]
// @PTN D:F11=0x145FD2AC0,SHandsRecoilCurveNoiseModifer::Init
// @PTN A:U(F11,-1):=G(0x148AE9DD0)@[?:0x8] {conf=med}
// @PTN I:L(F10,0)@[0x60:0x8] {conf=high,cs=0x145FD2A40,caller=F10} -> P(F11,0)
// @PTN E:L(F11,0)@[?:0x8] {conf=high,cs=0x145FD2ACE} -> A(F1,0)
// @PTN G:G(0x140369E60) -> F(F11)
// @PTN G:G(0x140369E60) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// --- Function: SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) ---
__int64 __fastcall SHandsRecoilCurveNoiseModifer::Init(__int64 a1)
{
  sub_140369E60(a1);
  *(_QWORD *)a1 = &off_148AE9DD0;
  *(float *)(a1 + 8) = 1065353216;
  *(float *)(a1 + 12) = 1065353216;
  *(float *)(a1 + 16) = 1065353216;
  return a1;
}

// --- End Function: SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) ---

// Incoming xrefs for SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0): SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0): sub_140369E60 (0x140369E60) [direct_call]
// @PTN D:F14=0x145FD45A0,SHandsRecoilCurveNoiseModifer::Init_0
// @PTN A:U(F14,-1):=G(0x148AE9C68)@[?:0x8] {conf=med}
// @PTN I:L(F17,0)@[0x48:0x8] {conf=high,cs=0x145FD5A96,caller=F17} -> P(F14,0)
// @PTN E:L(F14,0)@[?:0x8] {conf=high,cs=0x145FD45AE} -> A(F1,0)
// @PTN G:G(0x140369E60) -> F(F14)
// @PTN G:G(0x140369E60) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// --- Function: SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) ---
__int64 __fastcall SHandsRecoilCurveNoiseModifer::Init_0(__int64 a1)
{
  sub_140369E60((_QWORD *)a1);
  *(_QWORD *)a1 = &off_148AE9C68;
  *(float *)(a1 + 8) = 1065353216;
  *(float *)(a1 + 12) = 1065353216;
  *(float *)(a1 + 16) = 1065353216;
  return a1;
}

// --- End Function: SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call]
// @PTN D:F12=0x145FD2BD0,SActorProceduralHandsRecoilCurveDecayModifiersDef::Init
// @PTN A:U(F12,-1):=G(0x148AE9D08)@[?:0x8] {conf=med}
// @PTN I:L(F13,0)@[0xD8:0x8] {conf=high,cs=0x145FD2D89,caller=F13} -> P(F12,0)
// @PTN I:L(F13,0)@[0x128:0x8] {conf=high,cs=0x145FD2D9F,caller=F13} -> P(F12,0)
// @PTN I:L(F13,6)@[?:0x8] {conf=high,cs=0x145FD2E05,caller=F13} -> P(F12,0)
// @PTN I:L(F13,7)@[?:0x8] {conf=high,cs=0x145FD2E30,caller=F13} -> P(F12,0)
// @PTN E:L(F12,0)@[?:0x8] {conf=high,cs=0x145FD2BDE} -> A(F1,0)
// @PTN E:L(F12,0)@[0x8:0x8] {conf=high,cs=0x145FD2BFE} -> A(F3,0)
// @PTN E:L(F12,0)@[0x20:0x8] {conf=high,cs=0x145FD2C0F} -> A(F3,0)
// @PTN E:L(F12,0)@[0x38:0x8] {conf=high,cs=0x145FD2C20} -> A(F3,0)
// @PTN G:G(0x140369E60) -> F(F12)
// @PTN G:G(0x140369E60) -> F(F12)
// @PTN G:G(0x148AE9D08) -> F(F12)
// @PTN G:G(0x148AE9D08) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// --- Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) ---
__int64 __fastcall SActorProceduralHandsRecoilCurveDecayModifiersDef::Init(__int64 a1)
{
  sub_140369E60(a1);
  *(_QWORD *)a1 = off_148AE9D08;
  sub_14046E5B0(a1 + 8);
  sub_14046E5B0(a1 + 32);
  sub_14046E5B0(a1 + 56);
  *(float *)(a1 + 16) = 1065353216;
  *(float *)(a1 + 20) = 1065353216;
  *(float *)(a1 + 24) = 1065353216;
  *(float *)(a1 + 40) = 1065353216;
  *(float *)(a1 + 44) = 1065353216;
  *(float *)(a1 + 48) = 1065353216;
  *(float *)(a1 + 64) = 1065353216;
  *(float *)(a1 + 68) = 1065353216;
  *(float *)(a1 + 72) = 1065353216;
  return a1;
}

// --- End Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) ---

// Incoming xrefs for sub_145FD4610 (0x145FD4610): SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call]
// Outgoing xrefs for sub_145FD4610 (0x145FD4610): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call]
// @PTN D:F15=0x145FD4610,sub_145FD4610
// @PTN A:U(F15,-1):=G(0x148AE9E90)@[?:0x8] {conf=med}
// @PTN I:L(F16,0)@[0x8:0x8] {conf=high,cs=0x145FD57AE,caller=F16} -> P(F15,0)
// @PTN I:L(F16,0)@[0x40:0x8] {conf=high,cs=0x145FD57BF,caller=F16} -> P(F15,0)
// @PTN E:L(F15,0)@[?:0x8] {conf=high,cs=0x145FD461E} -> A(F1,0)
// @PTN E:L(F15,0)@[0x8:0x8] {conf=high,cs=0x145FD463E} -> A(F3,0)
// @PTN E:L(F15,0)@[0x20:0x8] {conf=high,cs=0x145FD464F} -> A(F3,0)
// @PTN G:G(0x140369E60) -> F(F15)
// @PTN G:G(0x140369E60) -> F(F15)
// @PTN G:G(0x148AE9E90) -> F(F15)
// @PTN G:G(0x148AE9E90) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// --- Function: sub_145FD4610 (0x145FD4610) ---
__int64 __fastcall sub_145FD4610(__int64 a1)
{
  sub_140369E60(a1);
  *(_QWORD *)a1 = off_148AE9E90;
  sub_14046E5B0(a1 + 8);
  sub_14046E5B0(a1 + 32);
  *(float *)(a1 + 16) = 1065353216;
  *(float *)(a1 + 20) = 1065353216;
  *(float *)(a1 + 24) = 1065353216;
  *(float *)(a1 + 40) = 1065353216;
  *(float *)(a1 + 44) = 1065353216;
  *(float *)(a1 + 48) = 1065353216;
  return a1;
}

// --- End Function: sub_145FD4610 (0x145FD4610) ---

// Incoming xrefs for SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780): sub_140369E60 (0x140369E60) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call]
// @PTN D:F16=0x145FD5780,SWeaponProceduralHeadRecoilCurveModifierDef::Init
// @PTN A:U(F16,-1):=G(0x148AE9EE0)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x290:0x8] {conf=high,cs=0x14317BAA5,caller=F6} -> P(F16,0)
// @PTN E:L(F16,0)@[?:0x8] {conf=high,cs=0x145FD578E} -> A(F1,0)
// @PTN E:L(F16,0)@[0x8:0x8] {conf=high,cs=0x145FD57AE} -> A(F15,0)
// @PTN E:L(F16,0)@[0x40:0x8] {conf=high,cs=0x145FD57BF} -> A(F15,0)
// @PTN G:G(0x140369E60) -> F(F16)
// @PTN G:G(0x140369E60) -> F(F16)
// @PTN G:G(0x148AE9EE0) -> F(F16)
// @PTN G:G(0x148AE9EE0) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// --- Function: SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) ---
__int64 __fastcall SWeaponProceduralHeadRecoilCurveModifierDef::Init(__int64 a1)
{
  sub_140369E60(a1);
  *(_QWORD *)a1 = off_148AE9EE0;
  sub_145FD4610(a1 + 8);
  sub_145FD4610(a1 + 64);
  *(float *)(a1 + 120) = 1065353216;
  *(float *)(a1 + 124) = 1065353216;
  *(float *)(a1 + 128) = 1065353216;
  return a1;
}

// --- End Function: SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) ---

// Incoming xrefs for SRecoilModifier::Init (0x14317BA10): SWeaponStats::Init (0x14317D700) [direct_call]
// Outgoing xrefs for SRecoilModifier::Init (0x14317BA10): SAimRecoilModifier::Init (0x143175900) [direct_call], SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call], SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call]
// @PTN D:F6=0x14317BA10,SRecoilModifier::Init
// @PTN A:U(F6,-1):=G(0x148AE9F88)@[?:0x8] {conf=med}
// @PTN A:U(F6,-1):=G(0x1485EF230)@[?:0x8] {conf=med}
// @PTN I:L(F7,0)@[0x38:0x8]:(__int64) {conf=high,cs=0x14317D75D,caller=F7} -> P(F6,0)
// @PTN E:L(F6,0)@[0x58:0x8] {conf=high,cs=0x14317BA8D} -> A(F5,0)
// @PTN E:L(F6,0)@[0x118:0x8] {conf=high,cs=0x14317BA99} -> A(F13,0)
// @PTN E:L(F6,0)@[0x290:0x8] {conf=high,cs=0x14317BAA5} -> A(F16,0)
// @PTN G:G(0x148AE9F88) -> F(F6)
// @PTN G:G(0x148AE9F88) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x143175900) -> F(F6)
// @PTN G:G(0x143175900) -> F(F6)
// @PTN G:G(0x145FD2CE0) -> F(F6)
// @PTN G:G(0x145FD2CE0) -> F(F6)
// @PTN G:G(0x145FD5780) -> F(F6)
// @PTN G:G(0x145FD5780) -> F(F6)
// --- Function: SRecoilModifier::Init (0x14317BA10) ---
__int64 __fastcall SRecoilModifier::Init(__int64 a1)
{
  *(_DWORD *)(a1 + 8) = 1065353216;
  *(_QWORD *)a1 = off_148AE9F88;
  *(_DWORD *)(a1 + 12) = 1065353216;
  *(_QWORD *)(a1 + 64) = &off_1485EF230;
  *(_DWORD *)(a1 + 16) = 1065353216;
  *(_DWORD *)(a1 + 20) = 1065353216;
  *(_DWORD *)(a1 + 24) = 1065353216;
  *(_DWORD *)(a1 + 28) = 1065353216;
  *(_DWORD *)(a1 + 32) = 1065353216;
  *(_DWORD *)(a1 + 36) = 1065353216;
  *(_DWORD *)(a1 + 40) = 1065353216;
  *(_DWORD *)(a1 + 44) = 1065353216;
  *(_DWORD *)(a1 + 48) = 1065353216;
  *(_DWORD *)(a1 + 52) = 1065353216;
  *(_DWORD *)(a1 + 56) = 1065353216;
  SAimRecoilModifier::Init((SAimRecoilModifier *)(a1 + 88));
  SActorProceduralHandsRecoilCurveModifiersDef::Init(a1 + 280);
  SWeaponProceduralHeadRecoilCurveModifierDef::Init(a1 + 656);
  *(_DWORD *)(a1 + 72) = 1065353216;
  *(_DWORD *)(a1 + 76) = 1065353216;
  *(_DWORD *)(a1 + 80) = 1065353216;
  return a1;
}

// --- End Function: SRecoilModifier::Init (0x14317BA10) ---

// Incoming xrefs for sub_145FD2960 (0x145FD2960): SAimRecoilModifier::Init (0x143175900) [direct_call]
// Outgoing xrefs for sub_145FD2960 (0x145FD2960): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call], SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) [direct_call]
// @PTN D:F10=0x145FD2960,sub_145FD2960
// @PTN A:U(F10,-1):=G(0x148AE9E30)@[?:0x8] {conf=med}
// @PTN I:L(F5,0)@[0x48:0x8]:(char *) {conf=high,cs=0x143175946,caller=F5} -> P(F10,0)
// @PTN E:L(F10,0)@[?:0x8] {conf=high,cs=0x145FD296E} -> A(F1,0)
// @PTN E:L(F10,0)@[0x20:0x8] {conf=high,cs=0x145FD29E8} -> A(F3,0)
// @PTN E:L(F10,0)@[0x38:0x8] {conf=high,cs=0x145FD29F9} -> A(F3,0)
// @PTN E:L(F10,0)@[0x60:0x8] {conf=high,cs=0x145FD2A40} -> A(F11,0)
// @PTN G:G(0x140369E60) -> F(F10)
// @PTN G:G(0x140369E60) -> F(F10)
// @PTN G:G(0x148AE9E30) -> F(F10)
// @PTN G:G(0x148AE9E30) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x145FD2AC0) -> F(F10)
// @PTN G:G(0x145FD2AC0) -> F(F10)
// --- Function: sub_145FD2960 (0x145FD2960) ---
__int64 __fastcall sub_145FD2960(__int64 a1)
{
  sub_140369E60((_QWORD *)a1);
  *(_QWORD *)a1 = off_148AE9E30;
  *(float *)(a1 + 8) = 1065353216;
  *(float *)(a1 + 12) = 1065353216;
  *(float *)(a1 + 16) = 1065353216;
  *(float *)(a1 + 20) = 1065353216;
  *(float *)(a1 + 24) = 1065353216;
  sub_14046E5B0(a1 + 32);
  sub_14046E5B0(a1 + 56);
  *(float *)(a1 + 80) = 1065353216;
  *(float *)(a1 + 84) = 1065353216;
  *(float *)(a1 + 88) = 1065353216;
  SHandsRecoilCurveNoiseModifer::Init(a1 + 96);
  *(float *)(a1 + 40) = 1065353216;
  *(float *)(a1 + 44) = 1065353216;
  *(float *)(a1 + 48) = 1065353216;
  *(float *)(a1 + 64) = 1065353216;
  *(float *)(a1 + 68) = 1065353216;
  *(float *)(a1 + 72) = 1065353216;
  return a1;
}

// --- End Function: sub_145FD2960 (0x145FD2960) ---

// Incoming xrefs for SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call], SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) [direct_call]
// @PTN D:F17=0x145FD5A10,SXYZCurvesWithMaxValuesModifer::Init
// @PTN A:U(F17,-1):=G(0x148AE9CB8)@[?:0x8] {conf=med}
// @PTN I:L(F13,0)@[0x10:0x8] {conf=high,cs=0x145FD2D2F,caller=F13} -> P(F17,0)
// @PTN I:L(F13,0)@[0x70:0x8] {conf=high,cs=0x145FD2D43,caller=F13} -> P(F17,0)
// @PTN I:L(F13,8)@[?:0x8] {conf=high,cs=0x145FD2DAC,caller=F13} -> P(F17,0)
// @PTN I:L(F13,9)@[?:0x8] {conf=high,cs=0x145FD2DDA,caller=F13} -> P(F17,0)
// @PTN E:L(F17,0)@[?:0x8] {conf=high,cs=0x145FD5A1E} -> A(F1,0)
// @PTN E:L(F17,0)@[0x18:0x8] {conf=high,cs=0x145FD5A74} -> A(F3,0)
// @PTN E:L(F17,0)@[0x30:0x8] {conf=high,cs=0x145FD5A85} -> A(F3,0)
// @PTN E:L(F17,0)@[0x48:0x8] {conf=high,cs=0x145FD5A96} -> A(F14,0)
// @PTN G:G(0x140369E60) -> F(F17)
// @PTN G:G(0x140369E60) -> F(F17)
// @PTN G:G(0x148AE9CB8) -> F(F17)
// @PTN G:G(0x148AE9CB8) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x145FD45A0) -> F(F17)
// @PTN G:G(0x145FD45A0) -> F(F17)
// --- Function: SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) ---
__int64 __fastcall SXYZCurvesWithMaxValuesModifer::Init(__int64 a1)
{
  sub_140369E60(a1);
  *(_QWORD *)a1 = off_148AE9CB8;
  *(float *)(a1 + 8) = 1065353216;
  *(float *)(a1 + 12) = 1065353216;
  *(float *)(a1 + 16) = 1065353216;
  sub_14046E5B0(a1 + 24);
  sub_14046E5B0(a1 + 48);
  SHandsRecoilCurveNoiseModifer::Init_0(a1 + 72);
  *(float *)(a1 + 32) = 1065353216;
  *(float *)(a1 + 36) = 1065353216;
  *(float *)(a1 + 40) = 1065353216;
  *(float *)(a1 + 56) = 1065353216;
  *(float *)(a1 + 60) = 1065353216;
  *(float *)(a1 + 64) = 1065353216;
  return a1;
}

// --- End Function: SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0): sub_140369E60 (0x140369E60) [direct_call], sub_14037BF20 (0x14037BF20) [direct_call], sub_14275A5F0 (0x14275A5F0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) [direct_call], SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// @PTN D:F13=0x145FD2CE0,SActorProceduralHandsRecoilCurveModifiersDef::Init
// @PTN A:U(F13,-1):=G(0x148AE9D70)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x118:0x8] {conf=high,cs=0x14317BA99,caller=F6} -> P(F13,0)
// @PTN E:L(F13,0)@[?:0x8] {conf=high,cs=0x145FD2CF4} -> A(F1,0)
// @PTN E:L(F13,0)@[0x10:0x8] {conf=high,cs=0x145FD2D2F} -> A(F17,0)
// @PTN E:L(F13,0)@[0x70:0x8] {conf=high,cs=0x145FD2D43} -> A(F17,0)
// @PTN E:L(F13,0)@[0xD8:0x8] {conf=high,cs=0x145FD2D89} -> A(F12,0)
// @PTN E:L(F13,0)@[0x128:0x8] {conf=high,cs=0x145FD2D9F} -> A(F12,0)
// @PTN E:L(F13,8)@[?:0x8] {conf=high,cs=0x145FD2DAC} -> A(F17,0)
// @PTN E:L(F13,0)@[0x10:0x8] {conf=high,cs=0x145FD2DC0} -> A(F9,0)
// @PTN E:L(F13,1)@[?:0x8] {conf=high,cs=0x145FD2DC0} -> A(F9,1)
// @PTN E:L(F13,8)@[?:0x8] {conf=high,cs=0x145FD2DCD} -> A(F4,0)
// @PTN E:L(F13,9)@[?:0x8] {conf=high,cs=0x145FD2DDA} -> A(F17,0)
// @PTN E:L(F13,0)@[0x70:0x8] {conf=high,cs=0x145FD2DEE} -> A(F9,0)
// @PTN E:L(F13,2)@[?:0x8] {conf=high,cs=0x145FD2DEE} -> A(F9,1)
// @PTN E:L(F13,9)@[?:0x8] {conf=high,cs=0x145FD2DFB} -> A(F4,0)
// @PTN E:L(F13,6)@[?:0x8] {conf=high,cs=0x145FD2E05} -> A(F12,0)
// @PTN E:L(F13,0)@[0xD8:0x8] {conf=high,cs=0x145FD2E1C} -> A(F8,0)
// @PTN E:L(F13,3)@[?:0x8] {conf=high,cs=0x145FD2E1C} -> A(F8,1)
// @PTN E:L(F13,6)@[?:0x8] {conf=high,cs=0x145FD2E26} -> A(F2,0)
// @PTN E:L(F13,7)@[?:0x8] {conf=high,cs=0x145FD2E30} -> A(F12,0)
// @PTN E:L(F13,0)@[0x128:0x8] {conf=high,cs=0x145FD2E47} -> A(F8,0)
// @PTN E:L(F13,4)@[?:0x8] {conf=high,cs=0x145FD2E47} -> A(F8,1)
// @PTN E:L(F13,7)@[?:0x8] {conf=high,cs=0x145FD2E51} -> A(F2,0)
// @PTN G:G(0x140369E60) -> F(F13)
// @PTN G:G(0x140369E60) -> F(F13)
// @PTN G:G(0x148AE9D70) -> F(F13)
// @PTN G:G(0x148AE9D70) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// --- Function: SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) ---
__int64 __fastcall SActorProceduralHandsRecoilCurveModifiersDef::Init(__int64 a1)
{
  __int64 v1; // rax
  __int64 v2; // rax
  __int64 v3; // rax
  __int64 v4; // rax
  _BYTE v6[80]; // [rsp+20h] [rbp-168h] BYREF
  _BYTE v7[80]; // [rsp+70h] [rbp-118h] BYREF
  _BYTE v8[96]; // [rsp+C0h] [rbp-C8h] BYREF
  _BYTE v9[104]; // [rsp+120h] [rbp-68h] BYREF

  sub_140369E60((_QWORD *)a1);
  *(_QWORD *)a1 = off_148AE9D70;
  *(float *)(a1 + 8) = 1065353216;
  SXYZCurvesWithMaxValuesModifer::Init(a1 + 16);
  SXYZCurvesWithMaxValuesModifer::Init(a1 + 112);
  *(float *)(a1 + 208) = 1065353216;
  *(float *)(a1 + 212) = 1065353216;
  SActorProceduralHandsRecoilCurveDecayModifiersDef::Init(a1 + 216);
  SActorProceduralHandsRecoilCurveDecayModifiersDef::Init(a1 + 296);
  v1 = SXYZCurvesWithMaxValuesModifer::Init((__int64)v8);
  SXYZCurvesWithMaxValuesModifer::CopyParams(a1 + 16, v1);
  sub_14275A5F0(v8);
  v2 = SXYZCurvesWithMaxValuesModifer::Init((__int64)v9);
  SXYZCurvesWithMaxValuesModifer::CopyParams(a1 + 112, v2);
  sub_14275A5F0(v9);
  v3 = SActorProceduralHandsRecoilCurveDecayModifiersDef::Init((__int64)v6);
  SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams(a1 + 216, v3);
  sub_14037BF20(v6);
  v4 = SActorProceduralHandsRecoilCurveDecayModifiersDef::Init((__int64)v7);
  SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams(a1 + 296, v4);
  sub_14037BF20(v7);
  return a1;
}

// --- End Function: SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) ---

