// Decompiled code dump generated by CodeDumper

// --------
#PTN v0
// @PTN LEGEND
// Nodes: L(F,i)=local i in function F; P(F,i)=param i of F; G(addr)=global at addr; F(Fx)=function Fx.
// Slices: @[off:len] in bytes; '?' unknown; '&' = address-of; '*' = deref; optional cast as :(type).
// A: alias inside function   => A: dst := src[@slice][mode][:cast] {meta}
// I: inbound (caller→this)   => I: origin -> P(F,i) {caller=F?,cs=0x...,conf=...}
// E: outbound (this→callee)  => E: origin -> A(F?,arg) [-> A(F?,arg)...] {cs=0x...,conf=...}
// G: global touch/summary    => G: F(F?) -> G(0xADDR)   or   G: F(writer) -> G(0xADDR) -> F(reader)
// Dictionary entry (per function block): // @PTN D:F?=0xEA,Name
// --------

// Types

struct UAmbisonicsEncodingSettings;

struct GFxVertexInterface_XY16iC32;

struct RBX::DataModelEmptySerialize;

struct DummyWatchItem;

struct game::device::Action;

struct PropertiesWidget::SoundPreviewPropertyItem;

struct std::_Node_rep;

struct CClearSurfacePass;

struct CryptoPP::PKCS1v15_SignatureMessageEncodingMethod;

struct physx::Sq::IncrementalAABBTreeNodePair;

struct RBX::Lua::WeakObjectRef;

struct CriMvEasyPlayer;

struct physx::PxsContactManager;

struct RBX::WeldAutoJointSurfacePair;

struct RBX::Graphics::Shadows::ShadowObjectBase;

#pragma pack(push, 1)
struct SHandsRecoilCurveNoiseModifer // sizeof=0x14
{                                       // XREF: SRecoilCurveModifierBlock78.noise/r
                                        // SXYZCurvesWithMaxValuesModifer.noise/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SRecoilCurveModifierBlock78 // sizeof=0x74
{                                       // XREF: SAimRecoilModifier.block/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
    float value3;
    float value4;
    int pad0;
    void *curve0;
    float value5;
    float value6;
    float value7;
    int pad1;
    void *curve1;
    float value8;
    float value9;
    float value10;
    int pad2;
    float value11;
    float value12;
    float value13;
    int pad3;
    struct SHandsRecoilCurveNoiseModifer noise;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SAimRecoilModifier // sizeof=0xBC
{                                       // XREF: SRecoilModifier.aim/r
    void *vfptr;
    void *curve0;
    float value0;
    float value1;
    void *curve1;
    float value2;
    float value3;
    void *curve2;
    float value4;
    float value5;
    float value6;
    float value7;
    float value8;
    float value9;
    struct SRecoilCurveModifierBlock78 block;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SActorProceduralHandsRecoilCurveDecayModifiersDef // sizeof=0x50
{                                       // XREF: SActorProceduralHandsRecoilCurveModifiersDef.decay0/r
                                        // SActorProceduralHandsRecoilCurveModifiersDef.decay1/r
    void *vfptr;
    void *curve0;
    float value0;
    float value1;
    float value2;
    int pad0;
    void *curve1;
    float value3;
    float value4;
    float value5;
    int pad1;
    void *curve2;
    float value6;
    float value7;
    float value8;
    int pad2;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SXYZCurvesWithMaxValuesModifer // sizeof=0x5C
{                                       // XREF: SActorProceduralHandsRecoilCurveModifiersDef.curves0/r
                                        // SActorProceduralHandsRecoilCurveModifiersDef.curves1/r
    void *vfptr;
    float max0;
    float max1;
    float max2;
    int pad0;
    void *curve0;
    float value0;
    float value1;
    float value2;
    int pad1;
    void *curve1;
    float value3;
    float value4;
    float value5;
    int pad2;
    struct SHandsRecoilCurveNoiseModifer noise;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SWeaponStatsModifierB // sizeof=0x1C
{                                       // XREF: SWeaponStatsLayout.modifier1/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
    unsigned __int8 flag0;
    unsigned __int8 pad0[3];
    float value3;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SActorProceduralHandsRecoilCurveModifiersDef // sizeof=0x170
{                                       // XREF: SRecoilModifier.hands/r
    void *vfptr;
    float value0;
    int pad0;
    struct SXYZCurvesWithMaxValuesModifer curves0;
    struct SXYZCurvesWithMaxValuesModifer curves1;
    float value1;
    float value2;
    struct SActorProceduralHandsRecoilCurveDecayModifiersDef decay0;
    struct SActorProceduralHandsRecoilCurveDecayModifiersDef decay1;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SWeaponStatsModifierC // sizeof=0x14
{                                       // XREF: SWeaponStatsLayout.modifier2/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SWeaponStatsModifierA // sizeof=0x20
{                                       // XREF: SWeaponStatsLayout.modifier0/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
    float value3;
    float value4;
    int value5;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SWeaponStatsModifierD // sizeof=0x16
{                                       // XREF: SWeaponStatsLayout.modifier3/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
    unsigned __int8 flag0;
    unsigned __int8 flag1;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SWeaponProceduralHeadRecoilCurveEntry38 // sizeof=0x38
{                                       // XREF: SWeaponProceduralHeadRecoilCurveModifierDef.entry0/r
                                        // SWeaponProceduralHeadRecoilCurveModifierDef.entry1/r
    void *vfptr;
    void *curve0;
    float value0;
    float value1;
    float value2;
    int pad0;
    void *curve1;
    float value3;
    float value4;
    float value5;
    int pad1;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SWeaponProceduralHeadRecoilCurveModifierDef // sizeof=0x88
{                                       // XREF: SRecoilModifier.head/r
    void *vfptr;
    struct SWeaponProceduralHeadRecoilCurveEntry38 entry0;
    struct SWeaponProceduralHeadRecoilCurveEntry38 entry1;
    float value0;
    float value1;
    float value2;
    int pad0;
};
#pragma pack(pop)

#pragma pack(push, 1)
struct SRecoilModifier // sizeof=0x30C
{                                       // XREF: SWeaponStatsLayout.recoil/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
    float value3;
    float value4;
    float value5;
    float value6;
    float value7;
    float value8;
    float value9;
    float value10;
    float value11;
    float value12;
    int pad0;
    void *curve0;
    float value13;
    float value14;
    float value15;
    int pad1;
    struct SAimRecoilModifier aim;
    struct SActorProceduralHandsRecoilCurveModifiersDef hands;
    struct SWeaponProceduralHeadRecoilCurveModifierDef head;
};
#pragma pack(pop)

typedef SWeaponStatsRecovered SWeaponStats;

struct SWeaponStatsLayout // sizeof=0x3B0
{
    void *vfptr;
    int value0;
    float value1;
    float value2;
    float value3;
    float value4;
    int value5;
    int value6;
    float value7;
    float value8;
    float value9;
    float value10;
    float value11;
    SRecoilModifier recoil;
    SWeaponStatsModifierA modifier0;
    SWeaponStatsModifierB modifier1;
    SWeaponStatsModifierC modifier2;
    SWeaponStatsModifierD modifier3;
    // padding byte
    // padding byte
    // padding byte
    // padding byte
    // padding byte
    // padding byte
};

#pragma pack(push, 1)
struct SWeaponStatsLayoutTest // sizeof=0x3C8
{
    void *vfptr;
    int value0;
    float value1;
    float value2;
    float value3;
    float value4;
    int value5;
    int value6;
    float value7;
    float value8;
    float value9;
    float value10;
    float value11;
    char tail[912];
};
#pragma pack(pop)

struct SHandsRecoilCurveNoiseModiferRecovered // sizeof=0x18
{                                       // XREF: SRecoilCurveModifierBlockRecovered.noise/r
                                        // SXYZCurvesWithMaxValuesModiferRecovered.noise/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
    int pad0;
};

struct SRecoilCurveModifierBlockRecovered // sizeof=0x78
{                                       // XREF: SAimRecoilModifierRecovered.block/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
    float value3;
    float value4;
    int pad0;
    void *curve0;
    float value5;
    float value6;
    float value7;
    int pad1;
    void *curve1;
    float value8;
    float value9;
    float value10;
    int pad2;
    float value11;
    float value12;
    float value13;
    int pad3;
    SHandsRecoilCurveNoiseModiferRecovered noise;
};

struct SAimRecoilModifierRecovered // sizeof=0xC0
{                                       // XREF: SRecoilModifierRecovered.aim/r
    void *vfptr;
    void *curve0;
    float value0;
    float value1;
    void *curve1;
    float value2;
    float value3;
    void *curve2;
    float value4;
    float value5;
    float value6;
    float value7;
    float value8;
    float value9;
    SRecoilCurveModifierBlockRecovered block;
};

struct SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered // sizeof=0x50
{                                       // XREF: SActorProceduralHandsRecoilCurveModifiersDef::Init/r
                                        // SActorProceduralHandsRecoilCurveModifiersDef::Init/r ...
    void *vfptr;
    void *curve0;
    float value0;
    float value1;
    float value2;
    int pad0;
    void *curve1;
    float value3;
    float value4;
    float value5;
    int pad1;
    void *curve2;
    float value6;
    float value7;
    float value8;
    int pad2;
};

struct SXYZCurvesWithMaxValuesModiferRecovered // sizeof=0x60
{                                       // XREF: SActorProceduralHandsRecoilCurveModifiersDef::Init/r
                                        // SActorProceduralHandsRecoilCurveModifiersDef::Init/r ...
    void *vfptr;
    float max0;                         // XREF: sub_145FDF0D0+13E/w
                                        // sub_145FDF0D0+28D/w
    float max1;                         // XREF: sub_145FDF0D0+19D/w
                                        // sub_145FDF0D0+2F2/w
    float max2;                         // XREF: sub_145FDF0D0+202/w
                                        // sub_145FDF0D0+357/w
    int pad0;
    void *curve0;
    float value0;
    float value1;
    float value2;
    int pad1;
    void *curve1;
    float value3;
    float value4;
    float value5;
    int pad2;
    SHandsRecoilCurveNoiseModiferRecovered noise;
};

struct SActorProceduralHandsRecoilCurveModifiersDefRecovered // sizeof=0x178
{                                       // XREF: SRecoilModifierRecovered.hands/r
    void *vfptr;
    float value0;
    int pad0;
    SXYZCurvesWithMaxValuesModiferRecovered curves0;
                                        // XREF: sub_145FDF0D0+13E/w
                                        // sub_145FDF0D0+19D/w ...
    SXYZCurvesWithMaxValuesModiferRecovered curves1;
                                        // XREF: sub_145FDF0D0+28D/w
                                        // sub_145FDF0D0+2F2/w ...
    float value1;
    float value2;
    SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered decay0;
    SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered decay1;
};

struct SWeaponProceduralHeadRecoilCurveEntryRecovered // sizeof=0x38
{                                       // XREF: SWeaponProceduralHeadRecoilCurveModifierDefRecovered.entry0/r
                                        // SWeaponProceduralHeadRecoilCurveModifierDefRecovered.entry1/r
    void *vfptr;
    void *curve0;
    float value0;
    float value1;
    float value2;
    int pad0;
    void *curve1;
    float value3;
    float value4;
    float value5;
    int pad1;
};

struct SWeaponProceduralHeadRecoilCurveModifierDefRecovered // sizeof=0x88
{                                       // XREF: SRecoilModifierRecovered.head/r
    void *vfptr;
    SWeaponProceduralHeadRecoilCurveEntryRecovered entry0;
    SWeaponProceduralHeadRecoilCurveEntryRecovered entry1;
    float value0;
    float value1;
    float value2;
    int pad0;
};

struct SRecoilModifierRecovered // sizeof=0x318
{                                       // XREF: sub_145FDF0D0/r
                                        // SWeaponStatsRecovered.recoil/r
    void *vfptr;
    float value0;
    float value1;
    float value2;
    float value3;
    float value4;
    float value5;
    float value6;
    float value7;
    float value8;
    float value9;
    float value10;
    float value11;
    float value12;
    int pad0;
    void *curve0;
    float value13;
    float value14;
    float value15;
    int pad1;
    SAimRecoilModifierRecovered aim;
    SActorProceduralHandsRecoilCurveModifiersDefRecovered hands;
                                        // XREF: sub_145FDF0D0+13E/w
                                        // sub_145FDF0D0+19D/w ...
    SWeaponProceduralHeadRecoilCurveModifierDefRecovered head;
};

struct SWeaponStatsModifierARecovered // sizeof=0x20
{                                       // XREF: SWeaponStatsRecovered.spreadModifier/r
                                        // SSpreadModifier/r
    void *vfptr;                        // XREF: sub_142AB0290+436/w
                                        // sub_142AB0840+436/w ...
    float spread0;                      // XREF: sub_143218440+14A/w
    float spread1;
    float spread2;
    float spread3;
    float spread4;                      // XREF: sub_143218440+15A/w
    int spread5_bits;                   // XREF: sub_143218440+18A/w
};

struct SWeaponStatsModifierBRecovered // sizeof=0x20
{                                       // XREF: SWeaponStatsRecovered.aimModifier/r
                                        // SAimModifier/r
    void *vfptr;                        // XREF: sub_142AB0290+42F/w
                                        // sub_142AB0840+42F/w ...
    float aim0;                         // XREF: sub_143218440+16A/w
    float aim1;                         // XREF: sub_143218440+1AA/w
    float aim2;                         // XREF: sub_143218440+17A/w
    unsigned __int8 enabled;            // XREF: sub_143218440+1DA/w
    unsigned __int8 pad0[3];
    float aim3;                         // XREF: sub_143218440+19A/w
    int pad1;
};

struct SWeaponStatsModifierCRecovered // sizeof=0x18
{                                       // XREF: SWeaponStatsRecovered.regenConsumerModifier/r
                                        // SRegenConsumerModifier/r
    void *vfptr;                        // XREF: sub_142AB0290+428/w
                                        // sub_142AB0840+428/w ...
    float regen0;                       // XREF: sub_143218440+1CA/w
    float regen1;                       // XREF: sub_143218440+1BA/w
    float regen2;                       // XREF: sub_143218440+1F7/w
    int pad0;
};

struct SWeaponStatsModifierDRecovered // sizeof=0x20
{                                       // XREF: SWeaponStatsRecovered.salvageModifier/r
                                        // SSalvageModifier/r
    void *vfptr;                        // XREF: sub_142AB0290+421/w
                                        // sub_142AB0840+421/w ...
    float salvage0;                     // XREF: sub_143218440+1E7/w
    float salvage1;                     // XREF: sub_143218440+21C/w
    float salvage2;                     // XREF: sub_143218440+214/w
    unsigned __int8 flag0;
    unsigned __int8 flag1;
    unsigned __int8 pad0[10];           // XREF: sub_143218440+207/w
                                        // sub_143218440+224/w
};

struct SWeaponStatsRecovered // sizeof=0x3C8
{                                       // XREF: sub_142AB0290/r
                                        // sub_142AB0840/r ...
    void *vfptr;                        // XREF: sub_142AB0290+449/w
                                        // sub_142AB0840+449/w ...
    int value0;                         // XREF: sub_142AB0290+22D/w
                                        // sub_142AB0840+22D/w ...
    float value1;                       // XREF: sub_142AB0290:loc_142AB04C2/w
                                        // sub_142AB0840:loc_142AB0A72/w ...
    float value2;                       // XREF: sub_142AB0290:loc_142AB04C9/w
                                        // sub_142AB0840:loc_142AB0A79/w
    float value3;                       // XREF: sub_142AB0290:loc_142AB04D0/w
                                        // sub_142AB0840:loc_142AB0A80/w
    float value4;                       // XREF: sub_142AB0290:loc_142AB04D7/w
                                        // sub_142AB0840:loc_142AB0A87/w
    int value5;                         // XREF: sub_142AB0290+252/w
                                        // sub_142AB0840+252/w ...
    int value6;                         // XREF: sub_142AB0290+25B/w
                                        // sub_142AB0840+25B/w ...
    float value7;                       // XREF: sub_142AB0290+264/w
                                        // sub_142AB0840+264/w ...
    float value8;                       // XREF: sub_142AB0290:loc_142AB04F9/w
                                        // sub_142AB0840:loc_142AB0AA9/w ...
    float value9;                       // XREF: sub_142AB0290:loc_142AB0500/w
                                        // sub_142AB0840:loc_142AB0AB0/w
    float value10;                      // XREF: sub_142AB0290:loc_142AB0507/w
                                        // sub_142AB0840:loc_142AB0AB7/w
    float value11;                      // XREF: sub_142AB0290:loc_142AB050E/w
                                        // sub_142AB0840:loc_142AB0ABE/w
    SRecoilModifierRecovered recoil;    // XREF: sub_142AB0290+41D/o
                                        // sub_142AB0840+41D/o ...
    SWeaponStatsModifierARecovered spreadModifier;
                                        // XREF: sub_142AB0290+436/w
                                        // sub_142AB0840+436/w ...
    SWeaponStatsModifierBRecovered aimModifier;
                                        // XREF: sub_142AB0290+42F/w
                                        // sub_142AB0840+42F/w ...
    SWeaponStatsModifierCRecovered regenConsumerModifier;
                                        // XREF: sub_142AB0290+428/w
                                        // sub_142AB0840+428/w ...
    SWeaponStatsModifierDRecovered salvageModifier;
                                        // XREF: sub_142AB0290+421/w
                                        // sub_142AB0840+421/w ...
};

typedef SWeaponStatsModifierARecovered SSpreadModifier;

typedef SWeaponStatsModifierBRecovered SAimModifier;

typedef SWeaponStatsModifierCRecovered SRegenConsumerModifier;

typedef SWeaponStatsModifierDRecovered SSalvageModifier;

// Start Function: 0x14317D700 (SWeaponStats::Init)
// Caller Depth: 0
// Callee/Ref Depth: 5
// Total Functions Found: 17
// Included Functions (17):
//   - sub_140369E60 (0x140369E60)
//   - sub_14037BF20 (0x14037BF20)
//   - sub_14046E5B0 (0x14046E5B0)
//   - sub_14275A5F0 (0x14275A5F0)
//   - SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0)
//   - SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0)
//   - SAimRecoilModifier::Init (0x143175900)
//   - SWeaponStats::Init (0x14317D700)
//   - SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0)
//   - SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0)
//   - SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0)
//   - sub_145FD4610 (0x145FD4610)
//   - SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780)
//   - SRecoilModifier::Init (0x14317BA10)
//   - sub_145FD2960 (0x145FD2960)
//   - SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10)
//   - SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0)
// Removed Functions: None
// ------------------------------------------------------------

// Incoming xrefs for sub_140369E60 (0x140369E60): sub_145FD2960 (0x145FD2960) [direct_call], SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call], SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call], SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for sub_140369E60 (0x140369E60): None
// @PTN D:F1=0x140369E60,sub_140369E60
// @PTN A:U(F1,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F11,0)@[?:0x8] {conf=high,cs=0x145FD2ACE,caller=F11} -> P(F1,0)
// @PTN I:L(F16,0)@[?:0x8] {conf=high,cs=0x145FD578E,caller=F16} -> P(F1,0)
// @PTN I:L(F17,0)@[?:0x8] {conf=high,cs=0x145FD5A1E,caller=F17} -> P(F1,0)
// @PTN I:L(F12,0)@[?:0x8] {conf=high,cs=0x145FD2BDE,caller=F12} -> P(F1,0)
// @PTN I:L(F15,0)@[?:0x8] {conf=high,cs=0x145FD461E,caller=F15} -> P(F1,0)
// @PTN I:L(F10,0)@[?:0x8] {conf=high,cs=0x145FD296E,caller=F10} -> P(F1,0)
// @PTN I:L(F13,0)@[?:0x8] {conf=high,cs=0x145FD2CF4,caller=F13} -> P(F1,0)
// @PTN I:L(F14,0)@[?:0x8] {conf=high,cs=0x145FD45AE,caller=F14} -> P(F1,0)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// --- Function: sub_140369E60 (0x140369E60) ---
char *__fastcall sub_140369E60(__int64 *a1)
{
  *a1 = (__int64)&off_1485D0AA8;
  return (char *)a1;
}

// --- End Function: sub_140369E60 (0x140369E60) ---

// Incoming xrefs for sub_14037BF20 (0x14037BF20): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for sub_14037BF20 (0x14037BF20): None
// @PTN D:F2=0x14037BF20,sub_14037BF20
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F13,6)@[?:0x50]& {conf=high,cs=0x145FD2E26,caller=F13} -> P(F2,0)
// @PTN I:L(F13,7)@[?:0x50]& {conf=high,cs=0x145FD2E51,caller=F13} -> P(F2,0)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// --- Function: sub_14037BF20 (0x14037BF20) ---
void *(__fastcall **__fastcall sub_14037BF20(_QWORD *a1))(RBX::DataModelEmptySerialize *__hidden this, unsigned int)
{
  a1[7] = &off_1485D0AA8;
  a1[4] = &off_1485D0AA8;
  a1[1] = &off_1485D0AA8;
  *a1 = &off_1485D0AA8;
  return &off_1485D0AA8;
}

// --- End Function: sub_14037BF20 (0x14037BF20) ---

// Incoming xrefs for sub_14046E5B0 (0x14046E5B0): sub_145FD2960 (0x145FD2960) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for sub_14046E5B0 (0x14046E5B0): None
// @PTN D:F3=0x14046E5B0,sub_14046E5B0
// @PTN A:U(F3,-1):=G(0x1485EF230)@[?:0x8] {conf=med}
// @PTN I:L(F17,0)@[0x18:0x8]* {conf=high,cs=0x145FD5A74,caller=F17} -> P(F3,0)
// @PTN I:L(F17,0)@[0x30:0x8]* {conf=high,cs=0x145FD5A85,caller=F17} -> P(F3,0)
// @PTN I:L(F12,0)@[0x8:0x8]* {conf=high,cs=0x145FD2BFE,caller=F12} -> P(F3,0)
// @PTN I:L(F12,0)@[0x20:0x8]* {conf=high,cs=0x145FD2C0F,caller=F12} -> P(F3,0)
// @PTN I:L(F12,0)@[0x38:0x8]* {conf=high,cs=0x145FD2C20,caller=F12} -> P(F3,0)
// @PTN I:L(F15,0)@[0x8:0x8]* {conf=high,cs=0x145FD463E,caller=F15} -> P(F3,0)
// @PTN I:L(F15,0)@[0x20:0x8]* {conf=high,cs=0x145FD464F,caller=F15} -> P(F3,0)
// @PTN I:L(F10,0)@[0x20:0x8]* {conf=high,cs=0x145FD29E8,caller=F10} -> P(F3,0)
// @PTN I:L(F10,0)@[0x38:0x8]* {conf=high,cs=0x145FD29F9,caller=F10} -> P(F3,0)
// @PTN G:G(0x1485EF230) -> F(F3)
// @PTN G:G(0x1485EF230) -> F(F3)
// @PTN G:G(0x1485EF230) -> F(F3)
// @PTN G:G(0x1485EF230) -> F(F3)
// --- Function: sub_14046E5B0 (0x14046E5B0) ---
__int64 *__fastcall sub_14046E5B0(__int64 *a1)
{
  *a1 = (__int64)&off_1485EF230;
  return a1;
}

// --- End Function: sub_14046E5B0 (0x14046E5B0) ---

// Incoming xrefs for sub_14275A5F0 (0x14275A5F0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for sub_14275A5F0 (0x14275A5F0): None
// @PTN D:F4=0x14275A5F0,sub_14275A5F0
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F13,8)@[?:0x60]& {conf=high,cs=0x145FD2DCD,caller=F13} -> P(F4,0)
// @PTN I:L(F13,9)@[?:0x60]& {conf=high,cs=0x145FD2DFB,caller=F13} -> P(F4,0)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// --- Function: sub_14275A5F0 (0x14275A5F0) ---
void *(__fastcall **__fastcall sub_14275A5F0(_QWORD *a1))(RBX::DataModelEmptySerialize *__hidden this, unsigned int)
{
  a1[9] = &off_1485D0AA8;
  a1[6] = &off_1485D0AA8;
  a1[3] = &off_1485D0AA8;
  *a1 = &off_1485D0AA8;
  return &off_1485D0AA8;
}

// --- End Function: sub_14275A5F0 (0x14275A5F0) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0): None
// @PTN D:F8=0x143181DF0,SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams
// @PTN A:U(F8,-1):=L(F8,1)@[0x18:0x4]* {conf=med}
// @PTN A:U(F8,-1):=L(F8,1)@[0x30:0x4]* {conf=med}
// @PTN A:U(F8,-1):=L(F8,1)@[0x48:0x4]* {conf=med}
// @PTN I:L(F13,0)@[0xD8:0x8]* {conf=high,cs=0x145FD2E1C,caller=F13} -> P(F8,0)
// @PTN I:L(F13,0)@[0x128:0x8]* {conf=high,cs=0x145FD2E47,caller=F13} -> P(F8,0)
// @PTN I:L(F13,3)@[?:0x8] {conf=high,cs=0x145FD2E1C,caller=F13} -> P(F8,1)
// @PTN I:L(F13,4)@[?:0x8] {conf=high,cs=0x145FD2E47,caller=F13} -> P(F8,1)
// --- Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) ---
SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered *__fastcall SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams(
        SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered *dst,
        const SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered *src)
{
  *(double *)&dst->value0 = *(double *)&src->value0;
  dst->value2 = src->value2;
  *(double *)&dst->value3 = *(double *)&src->value3;
  dst->value5 = src->value5;
  *(double *)&dst->value6 = *(double *)&src->value6;
  dst->value8 = src->value8;
  return dst;
}

// --- End Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) ---

// Incoming xrefs for SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0): None
// @PTN D:F9=0x1431833F0,SXYZCurvesWithMaxValuesModifer::CopyParams
// @PTN A:U(F9,-1):=L(F9,1)@[0x8:0x4]* {conf=med}
// @PTN A:U(F9,-1):=L(F9,1)@[0xC:0x4]* {conf=med}
// @PTN A:U(F9,-1):=L(F9,1)@[0x10:0x4]* {conf=med}
// @PTN A:U(F9,-1):=L(F9,1)@[0x28:0x4]* {conf=med}
// @PTN A:U(F9,-1):=L(F9,1)@[0x40:0x4]* {conf=med}
// @PTN A:U(F9,-1):=L(F9,1)@[0x48:0x4]* {conf=med}
// @PTN A:U(F9,-1):=L(F9,1)@[0x48:0x4]* {conf=med}
// @PTN A:U(F9,-1):=L(F9,1)@[0x48:0x4]* {conf=med}
// @PTN I:L(F13,0)@[0x10:0x8]* {conf=high,cs=0x145FD2DC0,caller=F13} -> P(F9,0)
// @PTN I:L(F13,0)@[0x70:0x8]* {conf=high,cs=0x145FD2DEE,caller=F13} -> P(F9,0)
// @PTN I:L(F13,1)@[?:0x8] {conf=high,cs=0x145FD2DC0,caller=F13} -> P(F9,1)
// @PTN I:L(F13,2)@[?:0x8] {conf=high,cs=0x145FD2DEE,caller=F13} -> P(F9,1)
// --- Function: SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) ---
SXYZCurvesWithMaxValuesModiferRecovered *__fastcall SXYZCurvesWithMaxValuesModifer::CopyParams(
        SXYZCurvesWithMaxValuesModiferRecovered *dst,
        const SXYZCurvesWithMaxValuesModiferRecovered *src)
{
  dst->max0 = src->max0;
  dst->max1 = src->max1;
  dst->max2 = src->max2;
  *(double *)&dst->value0 = *(double *)&src->value0;
  dst->value2 = src->value2;
  *(double *)&dst->value3 = *(double *)&src->value3;
  dst->value5 = src->value5;
  dst->noise.value0 = src->noise.value0;
  dst->noise.value1 = src->noise.value1;
  dst->noise.value2 = src->noise.value2;
  return dst;
}

// --- End Function: SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) ---

// Incoming xrefs for SAimRecoilModifier::Init (0x143175900): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SAimRecoilModifier::Init (0x143175900): sub_145FD2960 (0x145FD2960) [direct_call]
// @PTN D:F5=0x143175900,SAimRecoilModifier::Init
// @PTN A:U(F5,-1):=G(0x148AE9F40)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x58:0x8]* {conf=high,cs=0x14317BA8D,caller=F6} -> P(F5,0)
// @PTN E:L(F5,0)@[0x48:0x8]* {conf=high,cs=0x143175946} -> A(F10,0)
// @PTN G:G(0x148AE9F40) -> F(F5)
// @PTN G:G(0x148AE9F40) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x145FD2960) -> F(F5)
// @PTN G:G(0x145FD2960) -> F(F5)
// --- Function: SAimRecoilModifier::Init (0x143175900) ---
SAimRecoilModifierRecovered *__fastcall SAimRecoilModifier::Init(SAimRecoilModifierRecovered *this)
{
  this->value6 = 1.0;
  this->vfptr = off_148AE9F40;
  this->value7 = 1.0;
  this->curve0 = &off_14867BA00;
  this->curve1 = &off_14867BA00;
  this->curve2 = &off_14867BA00;
  this->value8 = 1.0;
  this->value9 = 1.0;
  sub_145FD2960(&this->block);
  this->value0 = 1.0;
  this->value1 = 1.0;
  this->value2 = 1.0;
  this->value3 = 1.0;
  this->value4 = 1.0;
  this->value5 = 1.0;
  return this;
}

// --- End Function: SAimRecoilModifier::Init (0x143175900) ---

// Incoming xrefs for SWeaponStats::Init (0x14317D700): None
// Outgoing xrefs for SWeaponStats::Init (0x14317D700): SRecoilModifier::Init (0x14317BA10) [direct_call]
// @PTN D:F7=0x14317D700,SWeaponStats::Init
// @PTN A:U(F7,-1):=G(0x148AEA0D8)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AE9FC8)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA008)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA048)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA090)@[?:0x8] {conf=med}
// @PTN E:L(F7,0)@[0x38:0x8]* {conf=high,cs=0x14317D75D} -> A(F6,0)
// @PTN G:G(0x148AEA0D8) -> F(F7)
// @PTN G:G(0x148AEA0D8) -> F(F7)
// @PTN G:G(0x14317BA10) -> F(F7)
// @PTN G:G(0x14317BA10) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// --- Function: SWeaponStats::Init (0x14317D700) ---
SWeaponStats *__fastcall SWeaponStats::Init(SWeaponStats *this)
{
  this->value1 = 1.0;
  this->value0 = 0;
  this->vfptr = off_148AEA0D8;
  *(_QWORD *)&this->value6 = 0;
  this->value2 = 1.0;
  this->value3 = 1.0;
  *(_QWORD *)&this->value4 = 1065353216;
  this->value8 = 1.0;
  this->value9 = 1.0;
  this->value10 = 1.0;
  this->value11 = 1.0;
  SRecoilModifier::Init(&this->recoil);
  this->spreadModifier.spread0 = 1.0;
  this->spreadModifier.vfptr = &off_148AE9FC8;
  this->aimModifier.vfptr = &off_148AEA008;
  this->regenConsumerModifier.vfptr = &off_148AEA048;
  this->salvageModifier.vfptr = &off_148AEA090;
  this->spreadModifier.spread1 = 1.0;
  this->spreadModifier.spread2 = 1.0;
  this->spreadModifier.spread3 = 1.0;
  *(_QWORD *)&this->spreadModifier.spread4 = 1065353216;
  this->aimModifier.aim0 = 1.0;
  this->aimModifier.aim1 = 1.0;
  this->aimModifier.aim2 = 1.0;
  this->aimModifier.enabled = 0;
  this->aimModifier.aim3 = 1.0;
  this->regenConsumerModifier.regen0 = 1.0;
  this->regenConsumerModifier.regen1 = 1.0;
  this->regenConsumerModifier.regen2 = 1.0;
  this->salvageModifier.salvage0 = 1.0;
  this->salvageModifier.salvage1 = 1.0;
  this->salvageModifier.salvage2 = 1.0;
  *(_WORD *)&this->salvageModifier.pad0[2] = 0;
  return this;
}

// --- End Function: SWeaponStats::Init (0x14317D700) ---

// Incoming xrefs for SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0): sub_145FD2960 (0x145FD2960) [direct_call]
// Outgoing xrefs for SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0): sub_140369E60 (0x140369E60) [direct_call]
// @PTN D:F11=0x145FD2AC0,SHandsRecoilCurveNoiseModifer::Init
// @PTN A:U(F11,-1):=G(0x148AE9DD0)@[?:0x8] {conf=med}
// @PTN I:L(F10,0)@[0x60:0x8]* {conf=high,cs=0x145FD2A40,caller=F10} -> P(F11,0)
// @PTN E:L(F11,0)@[?:0x8] {conf=high,cs=0x145FD2ACE} -> A(F1,0)
// @PTN G:G(0x140369E60) -> F(F11)
// @PTN G:G(0x140369E60) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// --- Function: SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) ---
SHandsRecoilCurveNoiseModiferRecovered *__fastcall SHandsRecoilCurveNoiseModifer::Init(
        SHandsRecoilCurveNoiseModiferRecovered *this)
{
  sub_140369E60((char *)this);
  this->vfptr = &off_148AE9DD0;
  this->value0 = 1065353216;
  this->value1 = 1065353216;
  this->value2 = 1065353216;
  return this;
}

// --- End Function: SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) ---

// Incoming xrefs for SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0): SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0): sub_140369E60 (0x140369E60) [direct_call]
// @PTN D:F14=0x145FD45A0,SHandsRecoilCurveNoiseModifer::Init_0
// @PTN A:U(F14,-1):=G(0x148AE9C68)@[?:0x8] {conf=med}
// @PTN I:L(F17,0)@[0x48:0x8]* {conf=high,cs=0x145FD5A96,caller=F17} -> P(F14,0)
// @PTN E:L(F14,0)@[?:0x8] {conf=high,cs=0x145FD45AE} -> A(F1,0)
// @PTN G:G(0x140369E60) -> F(F14)
// @PTN G:G(0x140369E60) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// --- Function: SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) ---
SHandsRecoilCurveNoiseModiferRecovered *__fastcall SHandsRecoilCurveNoiseModifer::Init_0(
        SHandsRecoilCurveNoiseModiferRecovered *this)
{
  sub_140369E60((__int64 *)this);
  this->vfptr = &off_148AE9C68;
  this->value0 = 1065353216;
  this->value1 = 1065353216;
  this->value2 = 1065353216;
  return this;
}

// --- End Function: SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call]
// @PTN D:F12=0x145FD2BD0,SActorProceduralHandsRecoilCurveDecayModifiersDef::Init
// @PTN A:U(F12,-1):=G(0x148AE9D08)@[?:0x8] {conf=med}
// @PTN I:L(F13,0)@[0xD8:0x8]* {conf=high,cs=0x145FD2D89,caller=F13} -> P(F12,0)
// @PTN I:L(F13,0)@[0x128:0x8]* {conf=high,cs=0x145FD2D9F,caller=F13} -> P(F12,0)
// @PTN I:L(F13,6)@[?:0x50]& {conf=high,cs=0x145FD2E05,caller=F13} -> P(F12,0)
// @PTN I:L(F13,7)@[?:0x50]& {conf=high,cs=0x145FD2E30,caller=F13} -> P(F12,0)
// @PTN E:L(F12,0)@[?:0x8] {conf=high,cs=0x145FD2BDE} -> A(F1,0)
// @PTN E:L(F12,0)@[0x8:0x8]* {conf=high,cs=0x145FD2BFE} -> A(F3,0)
// @PTN E:L(F12,0)@[0x20:0x8]* {conf=high,cs=0x145FD2C0F} -> A(F3,0)
// @PTN E:L(F12,0)@[0x38:0x8]* {conf=high,cs=0x145FD2C20} -> A(F3,0)
// @PTN G:G(0x140369E60) -> F(F12)
// @PTN G:G(0x140369E60) -> F(F12)
// @PTN G:G(0x148AE9D08) -> F(F12)
// @PTN G:G(0x148AE9D08) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// --- Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) ---
SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered *__fastcall SActorProceduralHandsRecoilCurveDecayModifiersDef::Init(
        SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered *this)
{
  sub_140369E60((char *)this);
  this->vfptr = off_148AE9D08;
  sub_14046E5B0((__int64 *)&this->curve0);
  sub_14046E5B0((__int64 *)&this->curve1);
  sub_14046E5B0((__int64 *)&this->curve2);
  this->value0 = 1065353216;
  this->value1 = 1065353216;
  this->value2 = 1065353216;
  this->value3 = 1065353216;
  this->value4 = 1065353216;
  this->value5 = 1065353216;
  this->value6 = 1065353216;
  this->value7 = 1065353216;
  this->value8 = 1065353216;
  return this;
}

// --- End Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) ---

// Incoming xrefs for sub_145FD4610 (0x145FD4610): SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call]
// Outgoing xrefs for sub_145FD4610 (0x145FD4610): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call]
// @PTN D:F15=0x145FD4610,sub_145FD4610
// @PTN A:U(F15,-1):=G(0x148AE9E90)@[?:0x8] {conf=med}
// @PTN I:L(F16,0)@[0x8:0x8]* {conf=high,cs=0x145FD57AE,caller=F16} -> P(F15,0)
// @PTN I:L(F16,0)@[0x40:0x8]* {conf=high,cs=0x145FD57BF,caller=F16} -> P(F15,0)
// @PTN E:L(F15,0)@[?:0x8] {conf=high,cs=0x145FD461E} -> A(F1,0)
// @PTN E:L(F15,0)@[0x8:0x8]* {conf=high,cs=0x145FD463E} -> A(F3,0)
// @PTN E:L(F15,0)@[0x20:0x8]* {conf=high,cs=0x145FD464F} -> A(F3,0)
// @PTN G:G(0x140369E60) -> F(F15)
// @PTN G:G(0x140369E60) -> F(F15)
// @PTN G:G(0x148AE9E90) -> F(F15)
// @PTN G:G(0x148AE9E90) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// --- Function: sub_145FD4610 (0x145FD4610) ---
SWeaponProceduralHeadRecoilCurveEntryRecovered *__fastcall sub_145FD4610(
        SWeaponProceduralHeadRecoilCurveEntryRecovered *this)
{
  sub_140369E60((char *)this);
  this->vfptr = off_148AE9E90;
  sub_14046E5B0((__int64 *)&this->curve0);
  sub_14046E5B0((__int64 *)&this->curve1);
  this->value0 = 1065353216;
  this->value1 = 1065353216;
  this->value2 = 1065353216;
  this->value3 = 1065353216;
  this->value4 = 1065353216;
  this->value5 = 1065353216;
  return this;
}

// --- End Function: sub_145FD4610 (0x145FD4610) ---

// Incoming xrefs for SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780): sub_140369E60 (0x140369E60) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call]
// @PTN D:F16=0x145FD5780,SWeaponProceduralHeadRecoilCurveModifierDef::Init
// @PTN A:U(F16,-1):=G(0x148AE9EE0)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x290:0x8]* {conf=high,cs=0x14317BAA5,caller=F6} -> P(F16,0)
// @PTN E:L(F16,0)@[?:0x8] {conf=high,cs=0x145FD578E} -> A(F1,0)
// @PTN E:L(F16,0)@[0x8:0x8]* {conf=high,cs=0x145FD57AE} -> A(F15,0)
// @PTN E:L(F16,0)@[0x40:0x8]* {conf=high,cs=0x145FD57BF} -> A(F15,0)
// @PTN G:G(0x140369E60) -> F(F16)
// @PTN G:G(0x140369E60) -> F(F16)
// @PTN G:G(0x148AE9EE0) -> F(F16)
// @PTN G:G(0x148AE9EE0) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// --- Function: SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) ---
SWeaponProceduralHeadRecoilCurveModifierDefRecovered *__fastcall SWeaponProceduralHeadRecoilCurveModifierDef::Init(
        SWeaponProceduralHeadRecoilCurveModifierDefRecovered *this)
{
  sub_140369E60((char *)this);
  this->vfptr = off_148AE9EE0;
  sub_145FD4610(&this->entry0);
  sub_145FD4610(&this->entry1);
  this->value0 = 1065353216;
  this->value1 = 1065353216;
  this->value2 = 1065353216;
  return this;
}

// --- End Function: SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) ---

// Incoming xrefs for SRecoilModifier::Init (0x14317BA10): SWeaponStats::Init (0x14317D700) [direct_call]
// Outgoing xrefs for SRecoilModifier::Init (0x14317BA10): SAimRecoilModifier::Init (0x143175900) [direct_call], SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call], SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call]
// @PTN D:F6=0x14317BA10,SRecoilModifier::Init
// @PTN A:U(F6,-1):=G(0x148AE9F88)@[?:0x8] {conf=med}
// @PTN A:U(F6,-1):=G(0x1485EF230)@[?:0x8] {conf=med}
// @PTN I:L(F7,0)@[0x38:0x8]* {conf=high,cs=0x14317D75D,caller=F7} -> P(F6,0)
// @PTN E:L(F6,0)@[0x58:0x8]* {conf=high,cs=0x14317BA8D} -> A(F5,0)
// @PTN E:L(F6,0)@[0x118:0x8]* {conf=high,cs=0x14317BA99} -> A(F13,0)
// @PTN E:L(F6,0)@[0x290:0x8]* {conf=high,cs=0x14317BAA5} -> A(F16,0)
// @PTN G:G(0x148AE9F88) -> F(F6)
// @PTN G:G(0x148AE9F88) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x143175900) -> F(F6)
// @PTN G:G(0x143175900) -> F(F6)
// @PTN G:G(0x145FD2CE0) -> F(F6)
// @PTN G:G(0x145FD2CE0) -> F(F6)
// @PTN G:G(0x145FD5780) -> F(F6)
// @PTN G:G(0x145FD5780) -> F(F6)
// --- Function: SRecoilModifier::Init (0x14317BA10) ---
SRecoilModifierRecovered *__fastcall SRecoilModifier::Init(SRecoilModifierRecovered *this)
{
  this->value0 = 1.0;
  this->vfptr = off_148AE9F88;
  this->value1 = 1.0;
  this->curve0 = &off_1485EF230;
  this->value2 = 1.0;
  this->value3 = 1.0;
  this->value4 = 1.0;
  this->value5 = 1.0;
  this->value6 = 1.0;
  this->value7 = 1.0;
  this->value8 = 1.0;
  this->value9 = 1.0;
  this->value10 = 1.0;
  this->value11 = 1.0;
  this->value12 = 1.0;
  SAimRecoilModifier::Init(&this->aim);
  SActorProceduralHandsRecoilCurveModifiersDef::Init(&this->hands);
  SWeaponProceduralHeadRecoilCurveModifierDef::Init(&this->head);
  this->value13 = 1.0;
  this->value14 = 1.0;
  this->value15 = 1.0;
  return this;
}

// --- End Function: SRecoilModifier::Init (0x14317BA10) ---

// Incoming xrefs for sub_145FD2960 (0x145FD2960): SAimRecoilModifier::Init (0x143175900) [direct_call]
// Outgoing xrefs for sub_145FD2960 (0x145FD2960): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call], SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) [direct_call]
// @PTN D:F10=0x145FD2960,sub_145FD2960
// @PTN A:U(F10,-1):=G(0x148AE9E30)@[?:0x8] {conf=med}
// @PTN I:L(F5,0)@[0x48:0x8]* {conf=high,cs=0x143175946,caller=F5} -> P(F10,0)
// @PTN E:L(F10,0)@[?:0x8] {conf=high,cs=0x145FD296E} -> A(F1,0)
// @PTN E:L(F10,0)@[0x20:0x8]* {conf=high,cs=0x145FD29E8} -> A(F3,0)
// @PTN E:L(F10,0)@[0x38:0x8]* {conf=high,cs=0x145FD29F9} -> A(F3,0)
// @PTN E:L(F10,0)@[0x60:0x8]* {conf=high,cs=0x145FD2A40} -> A(F11,0)
// @PTN G:G(0x140369E60) -> F(F10)
// @PTN G:G(0x140369E60) -> F(F10)
// @PTN G:G(0x148AE9E30) -> F(F10)
// @PTN G:G(0x148AE9E30) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x145FD2AC0) -> F(F10)
// @PTN G:G(0x145FD2AC0) -> F(F10)
// --- Function: sub_145FD2960 (0x145FD2960) ---
SRecoilCurveModifierBlockRecovered *__fastcall sub_145FD2960(SRecoilCurveModifierBlockRecovered *this)
{
  sub_140369E60((char *)this);
  this->vfptr = off_148AE9E30;
  this->value0 = 1065353216;
  this->value1 = 1065353216;
  this->value2 = 1065353216;
  this->value3 = 1065353216;
  this->value4 = 1065353216;
  sub_14046E5B0((__int64 *)&this->curve0);
  sub_14046E5B0((__int64 *)&this->curve1);
  this->value11 = 1065353216;
  this->value12 = 1065353216;
  this->value13 = 1065353216;
  SHandsRecoilCurveNoiseModifer::Init(&this->noise);
  this->value5 = 1065353216;
  this->value6 = 1065353216;
  this->value7 = 1065353216;
  this->value8 = 1065353216;
  this->value9 = 1065353216;
  this->value10 = 1065353216;
  return this;
}

// --- End Function: sub_145FD2960 (0x145FD2960) ---

// Incoming xrefs for SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call], SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) [direct_call]
// @PTN D:F17=0x145FD5A10,SXYZCurvesWithMaxValuesModifer::Init
// @PTN A:U(F17,-1):=G(0x148AE9CB8)@[?:0x8] {conf=med}
// @PTN I:L(F13,0)@[0x10:0x8]* {conf=high,cs=0x145FD2D2F,caller=F13} -> P(F17,0)
// @PTN I:L(F13,0)@[0x70:0x8]* {conf=high,cs=0x145FD2D43,caller=F13} -> P(F17,0)
// @PTN I:L(F13,8)@[?:0x60]& {conf=high,cs=0x145FD2DAC,caller=F13} -> P(F17,0)
// @PTN I:L(F13,9)@[?:0x60]& {conf=high,cs=0x145FD2DDA,caller=F13} -> P(F17,0)
// @PTN E:L(F17,0)@[?:0x8] {conf=high,cs=0x145FD5A1E} -> A(F1,0)
// @PTN E:L(F17,0)@[0x18:0x8]* {conf=high,cs=0x145FD5A74} -> A(F3,0)
// @PTN E:L(F17,0)@[0x30:0x8]* {conf=high,cs=0x145FD5A85} -> A(F3,0)
// @PTN E:L(F17,0)@[0x48:0x8]* {conf=high,cs=0x145FD5A96} -> A(F14,0)
// @PTN G:G(0x140369E60) -> F(F17)
// @PTN G:G(0x140369E60) -> F(F17)
// @PTN G:G(0x148AE9CB8) -> F(F17)
// @PTN G:G(0x148AE9CB8) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x145FD45A0) -> F(F17)
// @PTN G:G(0x145FD45A0) -> F(F17)
// --- Function: SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) ---
SXYZCurvesWithMaxValuesModiferRecovered *__fastcall SXYZCurvesWithMaxValuesModifer::Init(
        SXYZCurvesWithMaxValuesModiferRecovered *this)
{
  sub_140369E60((char *)this);
  this->vfptr = off_148AE9CB8;
  this->max0 = 1065353216;
  this->max1 = 1065353216;
  this->max2 = 1065353216;
  sub_14046E5B0((__int64 *)&this->curve0);
  sub_14046E5B0((__int64 *)&this->curve1);
  SHandsRecoilCurveNoiseModifer::Init_0(&this->noise);
  this->value0 = 1065353216;
  this->value1 = 1065353216;
  this->value2 = 1065353216;
  this->value3 = 1065353216;
  this->value4 = 1065353216;
  this->value5 = 1065353216;
  return this;
}

// --- End Function: SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0): sub_140369E60 (0x140369E60) [direct_call], sub_14037BF20 (0x14037BF20) [direct_call], sub_14275A5F0 (0x14275A5F0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) [direct_call], SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// @PTN D:F13=0x145FD2CE0,SActorProceduralHandsRecoilCurveModifiersDef::Init
// @PTN A:U(F13,-1):=G(0x148AE9D70)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x118:0x8]* {conf=high,cs=0x14317BA99,caller=F6} -> P(F13,0)
// @PTN E:L(F13,0)@[?:0x8] {conf=high,cs=0x145FD2CF4} -> A(F1,0)
// @PTN E:L(F13,0)@[0x10:0x8]* {conf=high,cs=0x145FD2D2F} -> A(F17,0)
// @PTN E:L(F13,0)@[0x70:0x8]* {conf=high,cs=0x145FD2D43} -> A(F17,0)
// @PTN E:L(F13,0)@[0xD8:0x8]* {conf=high,cs=0x145FD2D89} -> A(F12,0)
// @PTN E:L(F13,0)@[0x128:0x8]* {conf=high,cs=0x145FD2D9F} -> A(F12,0)
// @PTN E:L(F13,8)@[?:0x60]& {conf=high,cs=0x145FD2DAC} -> A(F17,0)
// @PTN E:L(F13,0)@[0x10:0x8]* {conf=high,cs=0x145FD2DC0} -> A(F9,0)
// @PTN E:L(F13,1)@[?:0x8] {conf=high,cs=0x145FD2DC0} -> A(F9,1)
// @PTN E:L(F13,8)@[?:0x60]& {conf=high,cs=0x145FD2DCD} -> A(F4,0)
// @PTN E:L(F13,9)@[?:0x60]& {conf=high,cs=0x145FD2DDA} -> A(F17,0)
// @PTN E:L(F13,0)@[0x70:0x8]* {conf=high,cs=0x145FD2DEE} -> A(F9,0)
// @PTN E:L(F13,2)@[?:0x8] {conf=high,cs=0x145FD2DEE} -> A(F9,1)
// @PTN E:L(F13,9)@[?:0x60]& {conf=high,cs=0x145FD2DFB} -> A(F4,0)
// @PTN E:L(F13,6)@[?:0x50]& {conf=high,cs=0x145FD2E05} -> A(F12,0)
// @PTN E:L(F13,0)@[0xD8:0x8]* {conf=high,cs=0x145FD2E1C} -> A(F8,0)
// @PTN E:L(F13,3)@[?:0x8] {conf=high,cs=0x145FD2E1C} -> A(F8,1)
// @PTN E:L(F13,6)@[?:0x50]& {conf=high,cs=0x145FD2E26} -> A(F2,0)
// @PTN E:L(F13,7)@[?:0x50]& {conf=high,cs=0x145FD2E30} -> A(F12,0)
// @PTN E:L(F13,0)@[0x128:0x8]* {conf=high,cs=0x145FD2E47} -> A(F8,0)
// @PTN E:L(F13,4)@[?:0x8] {conf=high,cs=0x145FD2E47} -> A(F8,1)
// @PTN E:L(F13,7)@[?:0x50]& {conf=high,cs=0x145FD2E51} -> A(F2,0)
// @PTN G:G(0x140369E60) -> F(F13)
// @PTN G:G(0x140369E60) -> F(F13)
// @PTN G:G(0x148AE9D70) -> F(F13)
// @PTN G:G(0x148AE9D70) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// --- Function: SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) ---
SActorProceduralHandsRecoilCurveModifiersDefRecovered *__fastcall SActorProceduralHandsRecoilCurveModifiersDef::Init(
        SActorProceduralHandsRecoilCurveModifiersDefRecovered *this)
{
  __int64 *v1; // rax
  __int64 *v2; // rax
  __int64 *v3; // rax
  __int64 *v4; // rax
  SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered v6; // [rsp+20h] [rbp-168h] BYREF
  SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered v7; // [rsp+70h] [rbp-118h] BYREF
  SXYZCurvesWithMaxValuesModiferRecovered v8; // [rsp+C0h] [rbp-C8h] BYREF
  SXYZCurvesWithMaxValuesModiferRecovered v9; // [rsp+120h] [rbp-68h] BYREF

  sub_140369E60((char *)this);
  this->vfptr = off_148AE9D70;
  this->value0 = 1065353216;
  SXYZCurvesWithMaxValuesModifer::Init(&this->curves0);
  SXYZCurvesWithMaxValuesModifer::Init(&this->curves1);
  this->value1 = 1065353216;
  this->value2 = 1065353216;
  SActorProceduralHandsRecoilCurveDecayModifiersDef::Init(&this->decay0);
  SActorProceduralHandsRecoilCurveDecayModifiersDef::Init(&this->decay1);
  v1 = (__int64 *)SXYZCurvesWithMaxValuesModifer::Init(&v8);
  SXYZCurvesWithMaxValuesModifer::CopyParams(&this->curves0, (const SXYZCurvesWithMaxValuesModiferRecovered *)v1);
  sub_14275A5F0(&v8);
  v2 = (__int64 *)SXYZCurvesWithMaxValuesModifer::Init(&v9);
  SXYZCurvesWithMaxValuesModifer::CopyParams(&this->curves1, (const SXYZCurvesWithMaxValuesModiferRecovered *)v2);
  sub_14275A5F0(&v9);
  v3 = (__int64 *)SActorProceduralHandsRecoilCurveDecayModifiersDef::Init(&v6);
  SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams(
    &this->decay0,
    (const SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered *)v3);
  sub_14037BF20(&v6);
  v4 = (__int64 *)SActorProceduralHandsRecoilCurveDecayModifiersDef::Init(&v7);
  SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams(
    &this->decay1,
    (const SActorProceduralHandsRecoilCurveDecayModifiersDefRecovered *)v4);
  sub_14037BF20(&v7);
  return this;
}

// --- End Function: SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) ---
