// Assembly dump generated by CodeDumper

// --------
#PTN v0
// @PTN LEGEND
// Nodes: L(F,i)=local i in function F; P(F,i)=param i of F; G(addr)=global at addr; F(Fx)=function Fx.
// Slices: @[off:len] in bytes; '?' unknown; '&' = address-of; '*' = deref; optional cast as :(type).
// A: alias inside function   => A: dst := src[@slice][mode][:cast] {meta}
// I: inbound (caller→this)   => I: origin -> P(F,i) {caller=F?,cs=0x...,conf=...}
// E: outbound (this→callee)  => E: origin -> A(F?,arg) [-> A(F?,arg)...] {cs=0x...,conf=...}
// G: global touch/summary    => G: F(F?) -> G(0xADDR)   or   G: F(writer) -> G(0xADDR) -> F(reader)
// Dictionary entry (per function block): // @PTN D:F?=0xEA,Name
// --------

// Start Function: 0x14317D700 (SWeaponStats::Init)
// Caller Depth: 0
// Callee/Ref Depth: 5
// Total Functions Found: 17
// Included Functions (17):
//   - sub_140369E60 (0x140369E60)
//   - sub_14037BF20 (0x14037BF20)
//   - sub_14046E5B0 (0x14046E5B0)
//   - sub_14275A5F0 (0x14275A5F0)
//   - SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0)
//   - SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0)
//   - SAimRecoilModifier::Init (0x143175900)
//   - SWeaponStats::Init (0x14317D700)
//   - SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0)
//   - SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0)
//   - SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0)
//   - sub_145FD4610 (0x145FD4610)
//   - SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780)
//   - SRecoilModifier::Init (0x14317BA10)
//   - sub_145FD2960 (0x145FD2960)
//   - SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10)
//   - SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0)
// Removed Functions: None
// ------------------------------------------------------------

// Incoming xrefs for sub_140369E60 (0x140369E60): sub_145FD2960 (0x145FD2960) [direct_call], SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call], SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call], SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for sub_140369E60 (0x140369E60): None
// @PTN D:F1=0x140369E60,sub_140369E60
// @PTN A:U(F1,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F11,0)@[?:0x8] {conf=high,cs=0x145FD2ACE,caller=F11} -> P(F1,0)
// @PTN I:L(F16,0)@[?:0x8] {conf=high,cs=0x145FD578E,caller=F16} -> P(F1,0)
// @PTN I:L(F17,0)@[?:0x8] {conf=high,cs=0x145FD5A1E,caller=F17} -> P(F1,0)
// @PTN I:L(F12,0)@[?:0x8] {conf=high,cs=0x145FD2BDE,caller=F12} -> P(F1,0)
// @PTN I:L(F15,0)@[?:0x8] {conf=high,cs=0x145FD461E,caller=F15} -> P(F1,0)
// @PTN I:L(F10,0)@[?:0x8] {conf=high,cs=0x145FD296E,caller=F10} -> P(F1,0)
// @PTN I:L(F13,0)@[?:0x8] {conf=high,cs=0x145FD2CF4,caller=F13} -> P(F1,0)
// @PTN I:L(F14,0)@[?:0x8] {conf=high,cs=0x145FD45AE,caller=F14} -> P(F1,0)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// @PTN G:G(0x1485D0AA8) -> F(F1)
// --- Function: sub_140369E60 (0x140369E60) ---
sub_140369E60:
0x140369E60: lea     rax, off_1485D0AA8
0x140369E67: mov     [rcx], rax
    // @PTN G:G(0x1485D0AA8) -> F(F1)
    // @PTN G:G(0x1485D0AA8) -> F(F1)
    // @PTN G:G(0x1485D0AA8) -> F(F1)
0x140369E6A: mov     rax, rcx
0x140369E6D: retn
// --- End Function: sub_140369E60 (0x140369E60) ---

// Incoming xrefs for sub_14037BF20 (0x14037BF20): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for sub_14037BF20 (0x14037BF20): None
// @PTN D:F2=0x14037BF20,sub_14037BF20
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F2,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F13,6)@[?:0x8] {conf=high,cs=0x145FD2E26,caller=F13} -> P(F2,0)
// @PTN I:L(F13,7)@[?:0x8] {conf=high,cs=0x145FD2E51,caller=F13} -> P(F2,0)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// @PTN G:G(0x1485D0AA8) -> F(F2)
// --- Function: sub_14037BF20 (0x14037BF20) ---
sub_14037BF20:
0x14037BF20: lea     rax, off_1485D0AA8
0x14037BF27: mov     [rcx+38h], rax
    // @PTN G:G(0x1485D0AA8) -> F(F2)
    // @PTN G:G(0x1485D0AA8) -> F(F2)
    // @PTN G:G(0x1485D0AA8) -> F(F2)
0x14037BF2B: mov     [rcx+20h], rax
    // @PTN G:G(0x1485D0AA8) -> F(F2)
    // @PTN G:G(0x1485D0AA8) -> F(F2)
    // @PTN G:G(0x1485D0AA8) -> F(F2)
0x14037BF2F: mov     [rcx+8], rax
    // @PTN G:G(0x1485D0AA8) -> F(F2)
    // @PTN G:G(0x1485D0AA8) -> F(F2)
    // @PTN G:G(0x1485D0AA8) -> F(F2)
0x14037BF33: mov     [rcx], rax
    // @PTN G:G(0x1485D0AA8) -> F(F2)
    // @PTN G:G(0x1485D0AA8) -> F(F2)
    // @PTN G:G(0x1485D0AA8) -> F(F2)
0x14037BF36: retn
// --- End Function: sub_14037BF20 (0x14037BF20) ---

// Incoming xrefs for sub_14046E5B0 (0x14046E5B0): sub_145FD2960 (0x145FD2960) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for sub_14046E5B0 (0x14046E5B0): None
// @PTN D:F3=0x14046E5B0,sub_14046E5B0
// @PTN A:U(F3,-1):=G(0x1485EF230)@[?:0x8] {conf=med}
// @PTN I:L(F17,0)@[0x18:0x8] {conf=high,cs=0x145FD5A74,caller=F17} -> P(F3,0)
// @PTN I:L(F17,0)@[0x30:0x8] {conf=high,cs=0x145FD5A85,caller=F17} -> P(F3,0)
// @PTN I:L(F12,0)@[0x8:0x8] {conf=high,cs=0x145FD2BFE,caller=F12} -> P(F3,0)
// @PTN I:L(F12,0)@[0x20:0x8] {conf=high,cs=0x145FD2C0F,caller=F12} -> P(F3,0)
// @PTN I:L(F12,0)@[0x38:0x8] {conf=high,cs=0x145FD2C20,caller=F12} -> P(F3,0)
// @PTN I:L(F15,0)@[0x8:0x8] {conf=high,cs=0x145FD463E,caller=F15} -> P(F3,0)
// @PTN I:L(F15,0)@[0x20:0x8] {conf=high,cs=0x145FD464F,caller=F15} -> P(F3,0)
// @PTN I:L(F10,0)@[0x20:0x8] {conf=high,cs=0x145FD29E8,caller=F10} -> P(F3,0)
// @PTN I:L(F10,0)@[0x38:0x8] {conf=high,cs=0x145FD29F9,caller=F10} -> P(F3,0)
// @PTN G:G(0x1485EF230) -> F(F3)
// @PTN G:G(0x1485EF230) -> F(F3)
// @PTN G:G(0x1485EF230) -> F(F3)
// --- Function: sub_14046E5B0 (0x14046E5B0) ---
sub_14046E5B0:
0x14046E5B0: lea     rax, off_1485EF230
0x14046E5B7: mov     [rcx], rax
    // @PTN G:G(0x1485EF230) -> F(F3)
    // @PTN G:G(0x1485EF230) -> F(F3)
    // @PTN G:G(0x1485EF230) -> F(F3)
0x14046E5BA: mov     rax, rcx
0x14046E5BD: retn
// --- End Function: sub_14046E5B0 (0x14046E5B0) ---

// Incoming xrefs for sub_14275A5F0 (0x14275A5F0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for sub_14275A5F0 (0x14275A5F0): None
// @PTN D:F4=0x14275A5F0,sub_14275A5F0
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN A:U(F4,-1):=G(0x1485D0AA8)@[?:0x8] {conf=med}
// @PTN I:L(F13,8)@[?:0x8] {conf=high,cs=0x145FD2DCD,caller=F13} -> P(F4,0)
// @PTN I:L(F13,9)@[?:0x8] {conf=high,cs=0x145FD2DFB,caller=F13} -> P(F4,0)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// @PTN G:G(0x1485D0AA8) -> F(F4)
// --- Function: sub_14275A5F0 (0x14275A5F0) ---
sub_14275A5F0:
0x14275A5F0: lea     rax, off_1485D0AA8
0x14275A5F7: mov     [rcx+48h], rax
    // @PTN G:G(0x1485D0AA8) -> F(F4)
    // @PTN G:G(0x1485D0AA8) -> F(F4)
    // @PTN G:G(0x1485D0AA8) -> F(F4)
0x14275A5FB: mov     [rcx+30h], rax
    // @PTN G:G(0x1485D0AA8) -> F(F4)
    // @PTN G:G(0x1485D0AA8) -> F(F4)
    // @PTN G:G(0x1485D0AA8) -> F(F4)
0x14275A5FF: mov     [rcx+18h], rax
    // @PTN G:G(0x1485D0AA8) -> F(F4)
    // @PTN G:G(0x1485D0AA8) -> F(F4)
    // @PTN G:G(0x1485D0AA8) -> F(F4)
0x14275A603: mov     [rcx], rax
    // @PTN G:G(0x1485D0AA8) -> F(F4)
    // @PTN G:G(0x1485D0AA8) -> F(F4)
    // @PTN G:G(0x1485D0AA8) -> F(F4)
0x14275A606: retn
// --- End Function: sub_14275A5F0 (0x14275A5F0) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0): None
// @PTN D:F8=0x143181DF0,SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams
// @PTN I:L(F13,0)@[0xD8:0x8] {conf=high,cs=0x145FD2E1C,caller=F13} -> P(F8,0)
// @PTN I:L(F13,0)@[0x128:0x8] {conf=high,cs=0x145FD2E47,caller=F13} -> P(F8,0)
// @PTN I:L(F13,3)@[?:0x8] {conf=high,cs=0x145FD2E1C,caller=F13} -> P(F8,1)
// @PTN I:L(F13,4)@[?:0x8] {conf=high,cs=0x145FD2E47,caller=F13} -> P(F8,1)
// --- Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) ---
SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams:
0x143181DF0: vmovsd  xmm0, qword ptr [rdx+10h]
0x143181DF5: vmovsd  qword ptr [rcx+10h], xmm0
0x143181DFA: mov     eax, [rdx+18h]
0x143181DFD: mov     [rcx+18h], eax
0x143181E00: vmovsd  xmm0, qword ptr [rdx+28h]
0x143181E05: vmovsd  qword ptr [rcx+28h], xmm0
0x143181E0A: mov     eax, [rdx+30h]
0x143181E0D: mov     [rcx+30h], eax
0x143181E10: vmovsd  xmm0, qword ptr [rdx+40h]
0x143181E15: vmovsd  qword ptr [rcx+40h], xmm0
0x143181E1A: mov     eax, [rdx+48h]
0x143181E1D: mov     [rcx+48h], eax
0x143181E20: mov     rax, rcx
0x143181E23: retn
// --- End Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) ---

// Incoming xrefs for SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0): None
// @PTN D:F9=0x1431833F0,SXYZCurvesWithMaxValuesModifer::CopyParams
// @PTN I:L(F13,0)@[0x10:0x8] {conf=high,cs=0x145FD2DC0,caller=F13} -> P(F9,0)
// @PTN I:L(F13,0)@[0x70:0x8] {conf=high,cs=0x145FD2DEE,caller=F13} -> P(F9,0)
// @PTN I:L(F13,1)@[?:0x8] {conf=high,cs=0x145FD2DC0,caller=F13} -> P(F9,1)
// @PTN I:L(F13,2)@[?:0x8] {conf=high,cs=0x145FD2DEE,caller=F13} -> P(F9,1)
// --- Function: SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) ---
SXYZCurvesWithMaxValuesModifer::CopyParams:
0x1431833F0: mov     eax, [rdx+8]
0x1431833F3: mov     [rcx+8], eax
0x1431833F6: mov     eax, [rdx+0Ch]
0x1431833F9: mov     [rcx+0Ch], eax
0x1431833FC: mov     eax, [rdx+10h]
0x1431833FF: mov     [rcx+10h], eax
0x143183402: vmovsd  xmm0, qword ptr [rdx+20h]
0x143183407: vmovsd  qword ptr [rcx+20h], xmm0
0x14318340C: mov     eax, [rdx+28h]
0x14318340F: mov     [rcx+28h], eax
0x143183412: vmovsd  xmm0, qword ptr [rdx+38h]
0x143183417: vmovsd  qword ptr [rcx+38h], xmm0
0x14318341C: mov     eax, [rdx+40h]
0x14318341F: mov     [rcx+40h], eax
0x143183422: mov     eax, [rdx+50h]
0x143183425: mov     [rcx+50h], eax
0x143183428: mov     eax, [rdx+54h]
0x14318342B: mov     [rcx+54h], eax
0x14318342E: mov     eax, [rdx+58h]
0x143183431: mov     [rcx+58h], eax
0x143183434: mov     rax, rcx
0x143183437: retn
// --- End Function: SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) ---

// Incoming xrefs for SAimRecoilModifier::Init (0x143175900): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SAimRecoilModifier::Init (0x143175900): sub_145FD2960 (0x145FD2960) [direct_call]
// @PTN D:F5=0x143175900,SAimRecoilModifier::Init
// @PTN A:U(F5,-1):=G(0x148AE9F40)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN A:U(F5,-1):=G(0x14867BA00)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x58:0x8] {conf=high,cs=0x14317BA8D,caller=F6} -> P(F5,0)
// @PTN E:L(F5,0)@[0x48:0x8]:(char *) {conf=high,cs=0x143175946} -> A(F10,0)
// @PTN G:G(0x148AE9F40) -> F(F5)
// @PTN G:G(0x148AE9F40) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x14867BA00) -> F(F5)
// @PTN G:G(0x145FD2960) -> F(F5)
// @PTN G:G(0x145FD2960) -> F(F5)
// --- Function: SAimRecoilModifier::Init (0x143175900) ---
SAimRecoilModifier::Init:
0x143175900: push    rbx
0x143175902: sub     rsp, 20h
0x143175906: lea     rax, off_148AE9F40
0x14317590D: mov     dword ptr [rcx+38h], 3F800000h
0x143175914: mov     [rcx], rax
    // @PTN G:G(0x148AE9F40) -> F(F5)
    // @PTN G:G(0x148AE9F40) -> F(F5)
0x143175917: mov     rbx, rcx
0x14317591A: lea     rax, off_14867BA00
0x143175921: mov     dword ptr [rcx+3Ch], 3F800000h
0x143175928: mov     [rcx+8], rax
    // @PTN G:G(0x14867BA00) -> F(F5)
    // @PTN G:G(0x14867BA00) -> F(F5)
    // @PTN G:G(0x14867BA00) -> F(F5)
0x14317592C: mov     [rcx+18h], rax
    // @PTN G:G(0x14867BA00) -> F(F5)
    // @PTN G:G(0x14867BA00) -> F(F5)
    // @PTN G:G(0x14867BA00) -> F(F5)
0x143175930: mov     [rcx+28h], rax
    // @PTN G:G(0x14867BA00) -> F(F5)
    // @PTN G:G(0x14867BA00) -> F(F5)
    // @PTN G:G(0x14867BA00) -> F(F5)
0x143175934: mov     dword ptr [rcx+40h], 3F800000h
0x14317593B: mov     dword ptr [rcx+44h], 3F800000h
0x143175942: add     rcx, 48h ; 'H'
0x143175946: call    sub_145FD2960
    // @PTN E:L(F5,0)@[0x48:0x8]:(char *) {conf=high} -> A(F10,0)
    // @PTN G:G(0x145FD2960) -> F(F5)
0x14317594B: mov     rax, rbx
0x14317594E: mov     dword ptr [rbx+10h], 3F800000h
0x143175955: mov     dword ptr [rbx+14h], 3F800000h
0x14317595C: mov     dword ptr [rbx+20h], 3F800000h
0x143175963: mov     dword ptr [rbx+24h], 3F800000h
0x14317596A: mov     dword ptr [rbx+30h], 3F800000h
0x143175971: mov     dword ptr [rbx+34h], 3F800000h
0x143175978: add     rsp, 20h
0x14317597C: pop     rbx
0x14317597D: retn
// --- End Function: SAimRecoilModifier::Init (0x143175900) ---

// Incoming xrefs for SWeaponStats::Init (0x14317D700): None
// Outgoing xrefs for SWeaponStats::Init (0x14317D700): SRecoilModifier::Init (0x14317BA10) [direct_call]
// @PTN D:F7=0x14317D700,SWeaponStats::Init
// @PTN A:U(F7,-1):=G(0x148AEA0D8)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AE9FC8)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA008)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA048)@[?:0x8] {conf=med}
// @PTN A:U(F7,-1):=G(0x148AEA090)@[?:0x8] {conf=med}
// @PTN E:L(F7,0)@[0x38:0x8]:(__int64) {conf=high,cs=0x14317D75D} -> A(F6,0)
// @PTN G:G(0x148AEA0D8) -> F(F7)
// @PTN G:G(0x148AEA0D8) -> F(F7)
// @PTN G:G(0x14317BA10) -> F(F7)
// @PTN G:G(0x14317BA10) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AE9FC8) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA008) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA048) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// @PTN G:G(0x148AEA090) -> F(F7)
// --- Function: SWeaponStats::Init (0x14317D700) ---
SWeaponStats::Init:
0x14317D700: mov     [rsp+arg_0], rbx
0x14317D705: push    rdi
0x14317D706: sub     rsp, 20h
0x14317D70A: xor     edi, edi
0x14317D70C: mov     dword ptr [rcx+0Ch], 3F800000h
0x14317D713: lea     rax, off_148AEA0D8
0x14317D71A: mov     [rcx+8], edi
0x14317D71D: mov     [rcx], rax
    // @PTN G:G(0x148AEA0D8) -> F(F7)
    // @PTN G:G(0x148AEA0D8) -> F(F7)
0x14317D720: mov     rbx, rcx
0x14317D723: mov     [rcx+20h], rdi
0x14317D727: mov     dword ptr [rcx+10h], 3F800000h
0x14317D72E: mov     dword ptr [rcx+14h], 3F800000h
0x14317D735: mov     qword ptr [rcx+18h], 3F800000h
0x14317D73D: mov     dword ptr [rcx+28h], 3F800000h
0x14317D744: mov     dword ptr [rcx+2Ch], 3F800000h
0x14317D74B: mov     dword ptr [rcx+30h], 3F800000h
0x14317D752: mov     dword ptr [rcx+34h], 3F800000h
0x14317D759: add     rcx, 38h ; '8'
0x14317D75D: call    SRecoilModifier__Init
    // @PTN E:L(F7,0)@[0x38:0x8]:(__int64) {conf=high} -> A(F6,0)
    // @PTN G:G(0x14317BA10) -> F(F7)
0x14317D762: lea     rax, off_148AE9FC8
0x14317D769: mov     dword ptr [rbx+358h], 3F800000h
0x14317D773: mov     [rbx+350h], rax
    // @PTN G:G(0x148AE9FC8) -> F(F7)
    // @PTN G:G(0x148AE9FC8) -> F(F7)
    // @PTN G:G(0x148AE9FC8) -> F(F7)
0x14317D77A: lea     rax, off_148AEA008
0x14317D781: mov     [rbx+370h], rax
    // @PTN G:G(0x148AEA008) -> F(F7)
    // @PTN G:G(0x148AEA008) -> F(F7)
    // @PTN G:G(0x148AEA008) -> F(F7)
0x14317D788: lea     rax, off_148AEA048
0x14317D78F: mov     [rbx+390h], rax
    // @PTN G:G(0x148AEA048) -> F(F7)
    // @PTN G:G(0x148AEA048) -> F(F7)
    // @PTN G:G(0x148AEA048) -> F(F7)
0x14317D796: lea     rax, off_148AEA090
0x14317D79D: mov     [rbx+3A8h], rax
    // @PTN G:G(0x148AEA090) -> F(F7)
    // @PTN G:G(0x148AEA090) -> F(F7)
    // @PTN G:G(0x148AEA090) -> F(F7)
0x14317D7A4: mov     rax, rbx
0x14317D7A7: mov     dword ptr [rbx+35Ch], 3F800000h
0x14317D7B1: mov     dword ptr [rbx+360h], 3F800000h
0x14317D7BB: mov     dword ptr [rbx+364h], 3F800000h
0x14317D7C5: mov     qword ptr [rbx+368h], 3F800000h
0x14317D7D0: mov     dword ptr [rbx+378h], 3F800000h
0x14317D7DA: mov     dword ptr [rbx+37Ch], 3F800000h
0x14317D7E4: mov     dword ptr [rbx+380h], 3F800000h
0x14317D7EE: mov     [rbx+384h], dil
0x14317D7F5: mov     dword ptr [rbx+388h], 3F800000h
0x14317D7FF: mov     dword ptr [rbx+398h], 3F800000h
0x14317D809: mov     dword ptr [rbx+39Ch], 3F800000h
0x14317D813: mov     dword ptr [rbx+3A0h], 3F800000h
0x14317D81D: mov     dword ptr [rbx+3B0h], 3F800000h
0x14317D827: mov     dword ptr [rbx+3B4h], 3F800000h
0x14317D831: mov     dword ptr [rbx+3B8h], 3F800000h
0x14317D83B: mov     [rbx+3C0h], di
0x14317D842: mov     rbx, [rsp+28h+arg_0]
0x14317D847: add     rsp, 20h
0x14317D84B: pop     rdi
0x14317D84C: retn
// --- End Function: SWeaponStats::Init (0x14317D700) ---

// Incoming xrefs for SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0): sub_145FD2960 (0x145FD2960) [direct_call]
// Outgoing xrefs for SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0): sub_140369E60 (0x140369E60) [direct_call]
// @PTN D:F11=0x145FD2AC0,SHandsRecoilCurveNoiseModifer::Init
// @PTN A:U(F11,-1):=G(0x148AE9DD0)@[?:0x8] {conf=med}
// @PTN I:L(F10,0)@[0x60:0x8] {conf=high,cs=0x145FD2A40,caller=F10} -> P(F11,0)
// @PTN E:L(F11,0)@[?:0x8] {conf=high,cs=0x145FD2ACE} -> A(F1,0)
// @PTN G:G(0x140369E60) -> F(F11)
// @PTN G:G(0x140369E60) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// @PTN G:G(0x148AE9DD0) -> F(F11)
// --- Function: SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) ---
SHandsRecoilCurveNoiseModifer::Init:
0x145FD2AC0: mov     [rsp+arg_0], rcx
0x145FD2AC5: sub     rsp, 28h
0x145FD2AC9: mov     rcx, [rsp+28h+arg_0]
0x145FD2ACE: call    sub_140369E60
    // @PTN E:L(F11,0)@[?:0x8] {conf=high} -> A(F1,0)
    // @PTN G:G(0x140369E60) -> F(F11)
0x145FD2AD3: mov     rax, [rsp+28h+arg_0]
0x145FD2AD8: lea     rcx, off_148AE9DD0
0x145FD2ADF: mov     [rax], rcx
    // @PTN G:G(0x148AE9DD0) -> F(F11)
    // @PTN G:G(0x148AE9DD0) -> F(F11)
    // @PTN G:G(0x148AE9DD0) -> F(F11)
0x145FD2AE2: mov     rax, [rsp+28h+arg_0]
0x145FD2AE7: vmovss  xmm0, cs:Y
0x145FD2AEF: vmovss  dword ptr [rax+8], xmm0
0x145FD2AF4: mov     rax, [rsp+28h+arg_0]
0x145FD2AF9: vmovss  xmm0, cs:Y
0x145FD2B01: vmovss  dword ptr [rax+0Ch], xmm0
0x145FD2B06: mov     rax, [rsp+28h+arg_0]
0x145FD2B0B: vmovss  xmm0, cs:Y
0x145FD2B13: vmovss  dword ptr [rax+10h], xmm0
0x145FD2B18: mov     rax, [rsp+28h+arg_0]
0x145FD2B1D: add     rsp, 28h
0x145FD2B21: retn
// --- End Function: SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) ---

// Incoming xrefs for SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0): SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// Outgoing xrefs for SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0): sub_140369E60 (0x140369E60) [direct_call]
// @PTN D:F14=0x145FD45A0,SHandsRecoilCurveNoiseModifer::Init_0
// @PTN A:U(F14,-1):=G(0x148AE9C68)@[?:0x8] {conf=med}
// @PTN I:L(F17,0)@[0x48:0x8] {conf=high,cs=0x145FD5A96,caller=F17} -> P(F14,0)
// @PTN E:L(F14,0)@[?:0x8] {conf=high,cs=0x145FD45AE} -> A(F1,0)
// @PTN G:G(0x140369E60) -> F(F14)
// @PTN G:G(0x140369E60) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// @PTN G:G(0x148AE9C68) -> F(F14)
// --- Function: SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) ---
SHandsRecoilCurveNoiseModifer::Init_0:
0x145FD45A0: mov     [rsp+arg_0], rcx
0x145FD45A5: sub     rsp, 28h
0x145FD45A9: mov     rcx, [rsp+28h+arg_0]
0x145FD45AE: call    sub_140369E60
    // @PTN E:L(F14,0)@[?:0x8] {conf=high} -> A(F1,0)
    // @PTN G:G(0x140369E60) -> F(F14)
0x145FD45B3: mov     rax, [rsp+28h+arg_0]
0x145FD45B8: lea     rcx, off_148AE9C68
0x145FD45BF: mov     [rax], rcx
    // @PTN G:G(0x148AE9C68) -> F(F14)
    // @PTN G:G(0x148AE9C68) -> F(F14)
    // @PTN G:G(0x148AE9C68) -> F(F14)
0x145FD45C2: mov     rax, [rsp+28h+arg_0]
0x145FD45C7: vmovss  xmm0, cs:Y
0x145FD45CF: vmovss  dword ptr [rax+8], xmm0
0x145FD45D4: mov     rax, [rsp+28h+arg_0]
0x145FD45D9: vmovss  xmm0, cs:Y
0x145FD45E1: vmovss  dword ptr [rax+0Ch], xmm0
0x145FD45E6: mov     rax, [rsp+28h+arg_0]
0x145FD45EB: vmovss  xmm0, cs:Y
0x145FD45F3: vmovss  dword ptr [rax+10h], xmm0
0x145FD45F8: mov     rax, [rsp+28h+arg_0]
0x145FD45FD: add     rsp, 28h
0x145FD4601: retn
// --- End Function: SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call]
// @PTN D:F12=0x145FD2BD0,SActorProceduralHandsRecoilCurveDecayModifiersDef::Init
// @PTN A:U(F12,-1):=G(0x148AE9D08)@[?:0x8] {conf=med}
// @PTN I:L(F13,0)@[0xD8:0x8] {conf=high,cs=0x145FD2D89,caller=F13} -> P(F12,0)
// @PTN I:L(F13,0)@[0x128:0x8] {conf=high,cs=0x145FD2D9F,caller=F13} -> P(F12,0)
// @PTN I:L(F13,6)@[?:0x8] {conf=high,cs=0x145FD2E05,caller=F13} -> P(F12,0)
// @PTN I:L(F13,7)@[?:0x8] {conf=high,cs=0x145FD2E30,caller=F13} -> P(F12,0)
// @PTN E:L(F12,0)@[?:0x8] {conf=high,cs=0x145FD2BDE} -> A(F1,0)
// @PTN E:L(F12,0)@[0x8:0x8] {conf=high,cs=0x145FD2BFE} -> A(F3,0)
// @PTN E:L(F12,0)@[0x20:0x8] {conf=high,cs=0x145FD2C0F} -> A(F3,0)
// @PTN E:L(F12,0)@[0x38:0x8] {conf=high,cs=0x145FD2C20} -> A(F3,0)
// @PTN G:G(0x140369E60) -> F(F12)
// @PTN G:G(0x140369E60) -> F(F12)
// @PTN G:G(0x148AE9D08) -> F(F12)
// @PTN G:G(0x148AE9D08) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// @PTN G:G(0x14046E5B0) -> F(F12)
// --- Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) ---
SActorProceduralHandsRecoilCurveDecayModifiersDef::Init:
0x145FD2BD0: mov     [rsp+arg_0], rcx
0x145FD2BD5: sub     rsp, 28h
0x145FD2BD9: mov     rcx, [rsp+28h+arg_0]
0x145FD2BDE: call    sub_140369E60
    // @PTN E:L(F12,0)@[?:0x8] {conf=high} -> A(F1,0)
    // @PTN G:G(0x140369E60) -> F(F12)
0x145FD2BE3: mov     rax, [rsp+28h+arg_0]
0x145FD2BE8: lea     rcx, off_148AE9D08
0x145FD2BEF: mov     [rax], rcx
    // @PTN G:G(0x148AE9D08) -> F(F12)
    // @PTN G:G(0x148AE9D08) -> F(F12)
0x145FD2BF2: mov     rax, [rsp+28h+arg_0]
0x145FD2BF7: add     rax, 8
0x145FD2BFB: mov     rcx, rax
0x145FD2BFE: call    sub_14046E5B0
    // @PTN E:L(F12,0)@[0x8:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F12)
0x145FD2C03: mov     rax, [rsp+28h+arg_0]
0x145FD2C08: add     rax, 20h ; ' '
0x145FD2C0C: mov     rcx, rax
0x145FD2C0F: call    sub_14046E5B0
    // @PTN E:L(F12,0)@[0x20:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F12)
0x145FD2C14: mov     rax, [rsp+28h+arg_0]
0x145FD2C19: add     rax, 38h ; '8'
0x145FD2C1D: mov     rcx, rax
0x145FD2C20: call    sub_14046E5B0
    // @PTN E:L(F12,0)@[0x38:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F12)
0x145FD2C25: mov     rax, [rsp+28h+arg_0]
0x145FD2C2A: vmovss  xmm0, cs:Y
0x145FD2C32: vmovss  dword ptr [rax+10h], xmm0
0x145FD2C37: mov     rax, [rsp+28h+arg_0]
0x145FD2C3C: vmovss  xmm0, cs:Y
0x145FD2C44: vmovss  dword ptr [rax+14h], xmm0
0x145FD2C49: mov     rax, [rsp+28h+arg_0]
0x145FD2C4E: vmovss  xmm0, cs:Y
0x145FD2C56: vmovss  dword ptr [rax+18h], xmm0
0x145FD2C5B: mov     rax, [rsp+28h+arg_0]
0x145FD2C60: vmovss  xmm0, cs:Y
0x145FD2C68: vmovss  dword ptr [rax+28h], xmm0
0x145FD2C6D: mov     rax, [rsp+28h+arg_0]
0x145FD2C72: vmovss  xmm0, cs:Y
0x145FD2C7A: vmovss  dword ptr [rax+2Ch], xmm0
0x145FD2C7F: mov     rax, [rsp+28h+arg_0]
0x145FD2C84: vmovss  xmm0, cs:Y
0x145FD2C8C: vmovss  dword ptr [rax+30h], xmm0
0x145FD2C91: mov     rax, [rsp+28h+arg_0]
0x145FD2C96: vmovss  xmm0, cs:Y
0x145FD2C9E: vmovss  dword ptr [rax+40h], xmm0
0x145FD2CA3: mov     rax, [rsp+28h+arg_0]
0x145FD2CA8: vmovss  xmm0, cs:Y
0x145FD2CB0: vmovss  dword ptr [rax+44h], xmm0
0x145FD2CB5: mov     rax, [rsp+28h+arg_0]
0x145FD2CBA: vmovss  xmm0, cs:Y
0x145FD2CC2: vmovss  dword ptr [rax+48h], xmm0
0x145FD2CC7: mov     rax, [rsp+28h+arg_0]
0x145FD2CCC: add     rsp, 28h
0x145FD2CD0: retn
// --- End Function: SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) ---

// Incoming xrefs for sub_145FD4610 (0x145FD4610): SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call]
// Outgoing xrefs for sub_145FD4610 (0x145FD4610): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call]
// @PTN D:F15=0x145FD4610,sub_145FD4610
// @PTN A:U(F15,-1):=G(0x148AE9E90)@[?:0x8] {conf=med}
// @PTN I:L(F16,0)@[0x8:0x8] {conf=high,cs=0x145FD57AE,caller=F16} -> P(F15,0)
// @PTN I:L(F16,0)@[0x40:0x8] {conf=high,cs=0x145FD57BF,caller=F16} -> P(F15,0)
// @PTN E:L(F15,0)@[?:0x8] {conf=high,cs=0x145FD461E} -> A(F1,0)
// @PTN E:L(F15,0)@[0x8:0x8] {conf=high,cs=0x145FD463E} -> A(F3,0)
// @PTN E:L(F15,0)@[0x20:0x8] {conf=high,cs=0x145FD464F} -> A(F3,0)
// @PTN G:G(0x140369E60) -> F(F15)
// @PTN G:G(0x140369E60) -> F(F15)
// @PTN G:G(0x148AE9E90) -> F(F15)
// @PTN G:G(0x148AE9E90) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// @PTN G:G(0x14046E5B0) -> F(F15)
// --- Function: sub_145FD4610 (0x145FD4610) ---
sub_145FD4610:
0x145FD4610: mov     [rsp+arg_0], rcx
0x145FD4615: sub     rsp, 28h
0x145FD4619: mov     rcx, [rsp+28h+arg_0]
0x145FD461E: call    sub_140369E60
    // @PTN E:L(F15,0)@[?:0x8] {conf=high} -> A(F1,0)
    // @PTN G:G(0x140369E60) -> F(F15)
0x145FD4623: mov     rax, [rsp+28h+arg_0]
0x145FD4628: lea     rcx, off_148AE9E90
0x145FD462F: mov     [rax], rcx
    // @PTN G:G(0x148AE9E90) -> F(F15)
    // @PTN G:G(0x148AE9E90) -> F(F15)
0x145FD4632: mov     rax, [rsp+28h+arg_0]
0x145FD4637: add     rax, 8
0x145FD463B: mov     rcx, rax
0x145FD463E: call    sub_14046E5B0
    // @PTN E:L(F15,0)@[0x8:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F15)
0x145FD4643: mov     rax, [rsp+28h+arg_0]
0x145FD4648: add     rax, 20h ; ' '
0x145FD464C: mov     rcx, rax
0x145FD464F: call    sub_14046E5B0
    // @PTN E:L(F15,0)@[0x20:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F15)
0x145FD4654: mov     rax, [rsp+28h+arg_0]
0x145FD4659: vmovss  xmm0, cs:Y
0x145FD4661: vmovss  dword ptr [rax+10h], xmm0
0x145FD4666: mov     rax, [rsp+28h+arg_0]
0x145FD466B: vmovss  xmm0, cs:Y
0x145FD4673: vmovss  dword ptr [rax+14h], xmm0
0x145FD4678: mov     rax, [rsp+28h+arg_0]
0x145FD467D: vmovss  xmm0, cs:Y
0x145FD4685: vmovss  dword ptr [rax+18h], xmm0
0x145FD468A: mov     rax, [rsp+28h+arg_0]
0x145FD468F: vmovss  xmm0, cs:Y
0x145FD4697: vmovss  dword ptr [rax+28h], xmm0
0x145FD469C: mov     rax, [rsp+28h+arg_0]
0x145FD46A1: vmovss  xmm0, cs:Y
0x145FD46A9: vmovss  dword ptr [rax+2Ch], xmm0
0x145FD46AE: mov     rax, [rsp+28h+arg_0]
0x145FD46B3: vmovss  xmm0, cs:Y
0x145FD46BB: vmovss  dword ptr [rax+30h], xmm0
0x145FD46C0: mov     rax, [rsp+28h+arg_0]
0x145FD46C5: add     rsp, 28h
0x145FD46C9: retn
// --- End Function: sub_145FD4610 (0x145FD4610) ---

// Incoming xrefs for SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780): sub_140369E60 (0x140369E60) [direct_call], sub_145FD4610 (0x145FD4610) [direct_call]
// @PTN D:F16=0x145FD5780,SWeaponProceduralHeadRecoilCurveModifierDef::Init
// @PTN A:U(F16,-1):=G(0x148AE9EE0)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x290:0x8] {conf=high,cs=0x14317BAA5,caller=F6} -> P(F16,0)
// @PTN E:L(F16,0)@[?:0x8] {conf=high,cs=0x145FD578E} -> A(F1,0)
// @PTN E:L(F16,0)@[0x8:0x8] {conf=high,cs=0x145FD57AE} -> A(F15,0)
// @PTN E:L(F16,0)@[0x40:0x8] {conf=high,cs=0x145FD57BF} -> A(F15,0)
// @PTN G:G(0x140369E60) -> F(F16)
// @PTN G:G(0x140369E60) -> F(F16)
// @PTN G:G(0x148AE9EE0) -> F(F16)
// @PTN G:G(0x148AE9EE0) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// @PTN G:G(0x145FD4610) -> F(F16)
// --- Function: SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) ---
SWeaponProceduralHeadRecoilCurveModifierDef::Init:
0x145FD5780: mov     [rsp+arg_0], rcx
0x145FD5785: sub     rsp, 28h
0x145FD5789: mov     rcx, [rsp+28h+arg_0]
0x145FD578E: call    sub_140369E60
    // @PTN E:L(F16,0)@[?:0x8] {conf=high} -> A(F1,0)
    // @PTN G:G(0x140369E60) -> F(F16)
0x145FD5793: mov     rax, [rsp+28h+arg_0]
0x145FD5798: lea     rcx, off_148AE9EE0
0x145FD579F: mov     [rax], rcx
    // @PTN G:G(0x148AE9EE0) -> F(F16)
    // @PTN G:G(0x148AE9EE0) -> F(F16)
0x145FD57A2: mov     rax, [rsp+28h+arg_0]
0x145FD57A7: add     rax, 8
0x145FD57AB: mov     rcx, rax
0x145FD57AE: call    sub_145FD4610
    // @PTN E:L(F16,0)@[0x8:0x8] {conf=high} -> A(F15,0)
    // @PTN G:G(0x145FD4610) -> F(F16)
0x145FD57B3: mov     rax, [rsp+28h+arg_0]
0x145FD57B8: add     rax, 40h ; '@'
0x145FD57BC: mov     rcx, rax
0x145FD57BF: call    sub_145FD4610
    // @PTN E:L(F16,0)@[0x40:0x8] {conf=high} -> A(F15,0)
    // @PTN G:G(0x145FD4610) -> F(F16)
0x145FD57C4: mov     rax, [rsp+28h+arg_0]
0x145FD57C9: vmovss  xmm0, cs:Y
0x145FD57D1: vmovss  dword ptr [rax+78h], xmm0
0x145FD57D6: mov     rax, [rsp+28h+arg_0]
0x145FD57DB: vmovss  xmm0, cs:Y
0x145FD57E3: vmovss  dword ptr [rax+7Ch], xmm0
0x145FD57E8: mov     rax, [rsp+28h+arg_0]
0x145FD57ED: vmovss  xmm0, cs:Y
0x145FD57F5: vmovss  dword ptr [rax+80h], xmm0
0x145FD57FD: mov     rax, [rsp+28h+arg_0]
0x145FD5802: add     rsp, 28h
0x145FD5806: retn
// --- End Function: SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) ---

// Incoming xrefs for SRecoilModifier::Init (0x14317BA10): SWeaponStats::Init (0x14317D700) [direct_call]
// Outgoing xrefs for SRecoilModifier::Init (0x14317BA10): SAimRecoilModifier::Init (0x143175900) [direct_call], SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call], SWeaponProceduralHeadRecoilCurveModifierDef::Init (0x145FD5780) [direct_call]
// @PTN D:F6=0x14317BA10,SRecoilModifier::Init
// @PTN A:U(F6,-1):=G(0x148AE9F88)@[?:0x8] {conf=med}
// @PTN A:U(F6,-1):=G(0x1485EF230)@[?:0x8] {conf=med}
// @PTN I:L(F7,0)@[0x38:0x8]:(__int64) {conf=high,cs=0x14317D75D,caller=F7} -> P(F6,0)
// @PTN E:L(F6,0)@[0x58:0x8] {conf=high,cs=0x14317BA8D} -> A(F5,0)
// @PTN E:L(F6,0)@[0x118:0x8] {conf=high,cs=0x14317BA99} -> A(F13,0)
// @PTN E:L(F6,0)@[0x290:0x8] {conf=high,cs=0x14317BAA5} -> A(F16,0)
// @PTN G:G(0x148AE9F88) -> F(F6)
// @PTN G:G(0x148AE9F88) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x1485EF230) -> F(F6)
// @PTN G:G(0x143175900) -> F(F6)
// @PTN G:G(0x143175900) -> F(F6)
// @PTN G:G(0x145FD2CE0) -> F(F6)
// @PTN G:G(0x145FD2CE0) -> F(F6)
// @PTN G:G(0x145FD5780) -> F(F6)
// @PTN G:G(0x145FD5780) -> F(F6)
// --- Function: SRecoilModifier::Init (0x14317BA10) ---
SRecoilModifier::Init:
0x14317BA10: push    rbx
0x14317BA12: sub     rsp, 20h
0x14317BA16: lea     rax, off_148AE9F88
0x14317BA1D: mov     dword ptr [rcx+8], 3F800000h
0x14317BA24: mov     [rcx], rax
    // @PTN G:G(0x148AE9F88) -> F(F6)
    // @PTN G:G(0x148AE9F88) -> F(F6)
0x14317BA27: mov     rbx, rcx
0x14317BA2A: lea     rax, off_1485EF230
0x14317BA31: mov     dword ptr [rcx+0Ch], 3F800000h
0x14317BA38: mov     [rcx+40h], rax
    // @PTN G:G(0x1485EF230) -> F(F6)
    // @PTN G:G(0x1485EF230) -> F(F6)
    // @PTN G:G(0x1485EF230) -> F(F6)
0x14317BA3C: mov     dword ptr [rcx+10h], 3F800000h
0x14317BA43: mov     dword ptr [rcx+14h], 3F800000h
0x14317BA4A: mov     dword ptr [rcx+18h], 3F800000h
0x14317BA51: mov     dword ptr [rcx+1Ch], 3F800000h
0x14317BA58: mov     dword ptr [rcx+20h], 3F800000h
0x14317BA5F: mov     dword ptr [rcx+24h], 3F800000h
0x14317BA66: mov     dword ptr [rcx+28h], 3F800000h
0x14317BA6D: mov     dword ptr [rcx+2Ch], 3F800000h
0x14317BA74: mov     dword ptr [rcx+30h], 3F800000h
0x14317BA7B: mov     dword ptr [rcx+34h], 3F800000h
0x14317BA82: mov     dword ptr [rcx+38h], 3F800000h
0x14317BA89: add     rcx, 58h ; 'X'
0x14317BA8D: call    SAimRecoilModifier__Init
    // @PTN E:L(F6,0)@[0x58:0x8] {conf=high} -> A(F5,0)
    // @PTN G:G(0x143175900) -> F(F6)
0x14317BA92: lea     rcx, [rbx+118h]
0x14317BA99: call    SActorProceduralHandsRecoilCurveModifiersDef__Init
    // @PTN E:L(F6,0)@[0x118:0x8] {conf=high} -> A(F13,0)
    // @PTN G:G(0x145FD2CE0) -> F(F6)
0x14317BA9E: lea     rcx, [rbx+290h]
0x14317BAA5: call    SWeaponProceduralHeadRecoilCurveModifierDef__Init
    // @PTN E:L(F6,0)@[0x290:0x8] {conf=high} -> A(F16,0)
    // @PTN G:G(0x145FD5780) -> F(F6)
0x14317BAAA: mov     rax, rbx
0x14317BAAD: mov     dword ptr [rbx+48h], 3F800000h
0x14317BAB4: mov     dword ptr [rbx+4Ch], 3F800000h
0x14317BABB: mov     dword ptr [rbx+50h], 3F800000h
0x14317BAC2: add     rsp, 20h
0x14317BAC6: pop     rbx
0x14317BAC7: retn
// --- End Function: SRecoilModifier::Init (0x14317BA10) ---

// Incoming xrefs for sub_145FD2960 (0x145FD2960): SAimRecoilModifier::Init (0x143175900) [direct_call]
// Outgoing xrefs for sub_145FD2960 (0x145FD2960): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call], SHandsRecoilCurveNoiseModifer::Init (0x145FD2AC0) [direct_call]
// @PTN D:F10=0x145FD2960,sub_145FD2960
// @PTN A:U(F10,-1):=G(0x148AE9E30)@[?:0x8] {conf=med}
// @PTN I:L(F5,0)@[0x48:0x8]:(char *) {conf=high,cs=0x143175946,caller=F5} -> P(F10,0)
// @PTN E:L(F10,0)@[?:0x8] {conf=high,cs=0x145FD296E} -> A(F1,0)
// @PTN E:L(F10,0)@[0x20:0x8] {conf=high,cs=0x145FD29E8} -> A(F3,0)
// @PTN E:L(F10,0)@[0x38:0x8] {conf=high,cs=0x145FD29F9} -> A(F3,0)
// @PTN E:L(F10,0)@[0x60:0x8] {conf=high,cs=0x145FD2A40} -> A(F11,0)
// @PTN G:G(0x140369E60) -> F(F10)
// @PTN G:G(0x140369E60) -> F(F10)
// @PTN G:G(0x148AE9E30) -> F(F10)
// @PTN G:G(0x148AE9E30) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x14046E5B0) -> F(F10)
// @PTN G:G(0x145FD2AC0) -> F(F10)
// @PTN G:G(0x145FD2AC0) -> F(F10)
// --- Function: sub_145FD2960 (0x145FD2960) ---
sub_145FD2960:
0x145FD2960: mov     [rsp+arg_0], rcx
0x145FD2965: sub     rsp, 28h
0x145FD2969: mov     rcx, [rsp+28h+arg_0]
0x145FD296E: call    sub_140369E60
    // @PTN E:L(F10,0)@[?:0x8] {conf=high} -> A(F1,0)
    // @PTN G:G(0x140369E60) -> F(F10)
0x145FD2973: mov     rax, [rsp+28h+arg_0]
0x145FD2978: lea     rcx, off_148AE9E30
0x145FD297F: mov     [rax], rcx
    // @PTN G:G(0x148AE9E30) -> F(F10)
    // @PTN G:G(0x148AE9E30) -> F(F10)
0x145FD2982: mov     rax, [rsp+28h+arg_0]
0x145FD2987: vmovss  xmm0, cs:Y
0x145FD298F: vmovss  dword ptr [rax+8], xmm0
0x145FD2994: mov     rax, [rsp+28h+arg_0]
0x145FD2999: vmovss  xmm0, cs:Y
0x145FD29A1: vmovss  dword ptr [rax+0Ch], xmm0
0x145FD29A6: mov     rax, [rsp+28h+arg_0]
0x145FD29AB: vmovss  xmm0, cs:Y
0x145FD29B3: vmovss  dword ptr [rax+10h], xmm0
0x145FD29B8: mov     rax, [rsp+28h+arg_0]
0x145FD29BD: vmovss  xmm0, cs:Y
0x145FD29C5: vmovss  dword ptr [rax+14h], xmm0
0x145FD29CA: mov     rax, [rsp+28h+arg_0]
0x145FD29CF: vmovss  xmm0, cs:Y
0x145FD29D7: vmovss  dword ptr [rax+18h], xmm0
0x145FD29DC: mov     rax, [rsp+28h+arg_0]
0x145FD29E1: add     rax, 20h ; ' '
0x145FD29E5: mov     rcx, rax
0x145FD29E8: call    sub_14046E5B0
    // @PTN E:L(F10,0)@[0x20:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F10)
0x145FD29ED: mov     rax, [rsp+28h+arg_0]
0x145FD29F2: add     rax, 38h ; '8'
0x145FD29F6: mov     rcx, rax
0x145FD29F9: call    sub_14046E5B0
    // @PTN E:L(F10,0)@[0x38:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F10)
0x145FD29FE: mov     rax, [rsp+28h+arg_0]
0x145FD2A03: vmovss  xmm0, cs:Y
0x145FD2A0B: vmovss  dword ptr [rax+50h], xmm0
0x145FD2A10: mov     rax, [rsp+28h+arg_0]
0x145FD2A15: vmovss  xmm0, cs:Y
0x145FD2A1D: vmovss  dword ptr [rax+54h], xmm0
0x145FD2A22: mov     rax, [rsp+28h+arg_0]
0x145FD2A27: vmovss  xmm0, cs:Y
0x145FD2A2F: vmovss  dword ptr [rax+58h], xmm0
0x145FD2A34: mov     rax, [rsp+28h+arg_0]
0x145FD2A39: add     rax, 60h ; '`'
0x145FD2A3D: mov     rcx, rax
0x145FD2A40: call    SHandsRecoilCurveNoiseModifer__Init
    // @PTN E:L(F10,0)@[0x60:0x8] {conf=high} -> A(F11,0)
    // @PTN G:G(0x145FD2AC0) -> F(F10)
0x145FD2A45: mov     rax, [rsp+28h+arg_0]
0x145FD2A4A: vmovss  xmm0, cs:Y
0x145FD2A52: vmovss  dword ptr [rax+28h], xmm0
0x145FD2A57: mov     rax, [rsp+28h+arg_0]
0x145FD2A5C: vmovss  xmm0, cs:Y
0x145FD2A64: vmovss  dword ptr [rax+2Ch], xmm0
0x145FD2A69: mov     rax, [rsp+28h+arg_0]
0x145FD2A6E: vmovss  xmm0, cs:Y
0x145FD2A76: vmovss  dword ptr [rax+30h], xmm0
0x145FD2A7B: mov     rax, [rsp+28h+arg_0]
0x145FD2A80: vmovss  xmm0, cs:Y
0x145FD2A88: vmovss  dword ptr [rax+40h], xmm0
0x145FD2A8D: mov     rax, [rsp+28h+arg_0]
0x145FD2A92: vmovss  xmm0, cs:Y
0x145FD2A9A: vmovss  dword ptr [rax+44h], xmm0
0x145FD2A9F: mov     rax, [rsp+28h+arg_0]
0x145FD2AA4: vmovss  xmm0, cs:Y
0x145FD2AAC: vmovss  dword ptr [rax+48h], xmm0
0x145FD2AB1: mov     rax, [rsp+28h+arg_0]
0x145FD2AB6: add     rsp, 28h
0x145FD2ABA: retn
// --- End Function: sub_145FD2960 (0x145FD2960) ---

// Incoming xrefs for SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10): SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) [direct_call]
// Outgoing xrefs for SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10): sub_140369E60 (0x140369E60) [direct_call], sub_14046E5B0 (0x14046E5B0) [direct_call], SHandsRecoilCurveNoiseModifer::Init_0 (0x145FD45A0) [direct_call]
// @PTN D:F17=0x145FD5A10,SXYZCurvesWithMaxValuesModifer::Init
// @PTN A:U(F17,-1):=G(0x148AE9CB8)@[?:0x8] {conf=med}
// @PTN I:L(F13,0)@[0x10:0x8] {conf=high,cs=0x145FD2D2F,caller=F13} -> P(F17,0)
// @PTN I:L(F13,0)@[0x70:0x8] {conf=high,cs=0x145FD2D43,caller=F13} -> P(F17,0)
// @PTN I:L(F13,8)@[?:0x8] {conf=high,cs=0x145FD2DAC,caller=F13} -> P(F17,0)
// @PTN I:L(F13,9)@[?:0x8] {conf=high,cs=0x145FD2DDA,caller=F13} -> P(F17,0)
// @PTN E:L(F17,0)@[?:0x8] {conf=high,cs=0x145FD5A1E} -> A(F1,0)
// @PTN E:L(F17,0)@[0x18:0x8] {conf=high,cs=0x145FD5A74} -> A(F3,0)
// @PTN E:L(F17,0)@[0x30:0x8] {conf=high,cs=0x145FD5A85} -> A(F3,0)
// @PTN E:L(F17,0)@[0x48:0x8] {conf=high,cs=0x145FD5A96} -> A(F14,0)
// @PTN G:G(0x140369E60) -> F(F17)
// @PTN G:G(0x140369E60) -> F(F17)
// @PTN G:G(0x148AE9CB8) -> F(F17)
// @PTN G:G(0x148AE9CB8) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x14046E5B0) -> F(F17)
// @PTN G:G(0x145FD45A0) -> F(F17)
// @PTN G:G(0x145FD45A0) -> F(F17)
// --- Function: SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) ---
SXYZCurvesWithMaxValuesModifer::Init:
0x145FD5A10: mov     [rsp+arg_0], rcx
0x145FD5A15: sub     rsp, 28h
0x145FD5A19: mov     rcx, [rsp+28h+arg_0]
0x145FD5A1E: call    sub_140369E60
    // @PTN E:L(F17,0)@[?:0x8] {conf=high} -> A(F1,0)
    // @PTN G:G(0x140369E60) -> F(F17)
0x145FD5A23: mov     rax, [rsp+28h+arg_0]
0x145FD5A28: lea     rcx, off_148AE9CB8
0x145FD5A2F: mov     [rax], rcx
    // @PTN G:G(0x148AE9CB8) -> F(F17)
    // @PTN G:G(0x148AE9CB8) -> F(F17)
0x145FD5A32: mov     rax, [rsp+28h+arg_0]
0x145FD5A37: vmovss  xmm0, cs:Y
0x145FD5A3F: vmovss  dword ptr [rax+8], xmm0
0x145FD5A44: mov     rax, [rsp+28h+arg_0]
0x145FD5A49: vmovss  xmm0, cs:Y
0x145FD5A51: vmovss  dword ptr [rax+0Ch], xmm0
0x145FD5A56: mov     rax, [rsp+28h+arg_0]
0x145FD5A5B: vmovss  xmm0, cs:Y
0x145FD5A63: vmovss  dword ptr [rax+10h], xmm0
0x145FD5A68: mov     rax, [rsp+28h+arg_0]
0x145FD5A6D: add     rax, 18h
0x145FD5A71: mov     rcx, rax
0x145FD5A74: call    sub_14046E5B0
    // @PTN E:L(F17,0)@[0x18:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F17)
0x145FD5A79: mov     rax, [rsp+28h+arg_0]
0x145FD5A7E: add     rax, 30h ; '0'
0x145FD5A82: mov     rcx, rax
0x145FD5A85: call    sub_14046E5B0
    // @PTN E:L(F17,0)@[0x30:0x8] {conf=high} -> A(F3,0)
    // @PTN G:G(0x14046E5B0) -> F(F17)
0x145FD5A8A: mov     rax, [rsp+28h+arg_0]
0x145FD5A8F: add     rax, 48h ; 'H'
0x145FD5A93: mov     rcx, rax
0x145FD5A96: call    SHandsRecoilCurveNoiseModifer__Init_0
    // @PTN E:L(F17,0)@[0x48:0x8] {conf=high} -> A(F14,0)
    // @PTN G:G(0x145FD45A0) -> F(F17)
0x145FD5A9B: mov     rax, [rsp+28h+arg_0]
0x145FD5AA0: vmovss  xmm0, cs:Y
0x145FD5AA8: vmovss  dword ptr [rax+20h], xmm0
0x145FD5AAD: mov     rax, [rsp+28h+arg_0]
0x145FD5AB2: vmovss  xmm0, cs:Y
0x145FD5ABA: vmovss  dword ptr [rax+24h], xmm0
0x145FD5ABF: mov     rax, [rsp+28h+arg_0]
0x145FD5AC4: vmovss  xmm0, cs:Y
0x145FD5ACC: vmovss  dword ptr [rax+28h], xmm0
0x145FD5AD1: mov     rax, [rsp+28h+arg_0]
0x145FD5AD6: vmovss  xmm0, cs:Y
0x145FD5ADE: vmovss  dword ptr [rax+38h], xmm0
0x145FD5AE3: mov     rax, [rsp+28h+arg_0]
0x145FD5AE8: vmovss  xmm0, cs:Y
0x145FD5AF0: vmovss  dword ptr [rax+3Ch], xmm0
0x145FD5AF5: mov     rax, [rsp+28h+arg_0]
0x145FD5AFA: vmovss  xmm0, cs:Y
0x145FD5B02: vmovss  dword ptr [rax+40h], xmm0
0x145FD5B07: mov     rax, [rsp+28h+arg_0]
0x145FD5B0C: add     rsp, 28h
0x145FD5B10: retn
// --- End Function: SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) ---

// Incoming xrefs for SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0): SRecoilModifier::Init (0x14317BA10) [direct_call]
// Outgoing xrefs for SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0): sub_140369E60 (0x140369E60) [direct_call], sub_14037BF20 (0x14037BF20) [direct_call], sub_14275A5F0 (0x14275A5F0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::CopyParams (0x143181DF0) [direct_call], SXYZCurvesWithMaxValuesModifer::CopyParams (0x1431833F0) [direct_call], SActorProceduralHandsRecoilCurveDecayModifiersDef::Init (0x145FD2BD0) [direct_call], SXYZCurvesWithMaxValuesModifer::Init (0x145FD5A10) [direct_call]
// @PTN D:F13=0x145FD2CE0,SActorProceduralHandsRecoilCurveModifiersDef::Init
// @PTN A:U(F13,-1):=G(0x148AE9D70)@[?:0x8] {conf=med}
// @PTN I:L(F6,0)@[0x118:0x8] {conf=high,cs=0x14317BA99,caller=F6} -> P(F13,0)
// @PTN E:L(F13,0)@[?:0x8] {conf=high,cs=0x145FD2CF4} -> A(F1,0)
// @PTN E:L(F13,0)@[0x10:0x8] {conf=high,cs=0x145FD2D2F} -> A(F17,0)
// @PTN E:L(F13,0)@[0x70:0x8] {conf=high,cs=0x145FD2D43} -> A(F17,0)
// @PTN E:L(F13,0)@[0xD8:0x8] {conf=high,cs=0x145FD2D89} -> A(F12,0)
// @PTN E:L(F13,0)@[0x128:0x8] {conf=high,cs=0x145FD2D9F} -> A(F12,0)
// @PTN E:L(F13,8)@[?:0x8] {conf=high,cs=0x145FD2DAC} -> A(F17,0)
// @PTN E:L(F13,0)@[0x10:0x8] {conf=high,cs=0x145FD2DC0} -> A(F9,0)
// @PTN E:L(F13,1)@[?:0x8] {conf=high,cs=0x145FD2DC0} -> A(F9,1)
// @PTN E:L(F13,8)@[?:0x8] {conf=high,cs=0x145FD2DCD} -> A(F4,0)
// @PTN E:L(F13,9)@[?:0x8] {conf=high,cs=0x145FD2DDA} -> A(F17,0)
// @PTN E:L(F13,0)@[0x70:0x8] {conf=high,cs=0x145FD2DEE} -> A(F9,0)
// @PTN E:L(F13,2)@[?:0x8] {conf=high,cs=0x145FD2DEE} -> A(F9,1)
// @PTN E:L(F13,9)@[?:0x8] {conf=high,cs=0x145FD2DFB} -> A(F4,0)
// @PTN E:L(F13,6)@[?:0x8] {conf=high,cs=0x145FD2E05} -> A(F12,0)
// @PTN E:L(F13,0)@[0xD8:0x8] {conf=high,cs=0x145FD2E1C} -> A(F8,0)
// @PTN E:L(F13,3)@[?:0x8] {conf=high,cs=0x145FD2E1C} -> A(F8,1)
// @PTN E:L(F13,6)@[?:0x8] {conf=high,cs=0x145FD2E26} -> A(F2,0)
// @PTN E:L(F13,7)@[?:0x8] {conf=high,cs=0x145FD2E30} -> A(F12,0)
// @PTN E:L(F13,0)@[0x128:0x8] {conf=high,cs=0x145FD2E47} -> A(F8,0)
// @PTN E:L(F13,4)@[?:0x8] {conf=high,cs=0x145FD2E47} -> A(F8,1)
// @PTN E:L(F13,7)@[?:0x8] {conf=high,cs=0x145FD2E51} -> A(F2,0)
// @PTN G:G(0x140369E60) -> F(F13)
// @PTN G:G(0x140369E60) -> F(F13)
// @PTN G:G(0x148AE9D70) -> F(F13)
// @PTN G:G(0x148AE9D70) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x145FD5A10) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x1431833F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x14275A5F0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x145FD2BD0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x143181DF0) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// @PTN G:G(0x14037BF20) -> F(F13)
// --- Function: SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) ---
SActorProceduralHandsRecoilCurveModifiersDef::Init:
0x145FD2CE0: mov     [rsp+arg_0], rcx
0x145FD2CE5: sub     rsp, 188h
0x145FD2CEC: mov     rcx, [rsp+188h+arg_0]
0x145FD2CF4: call    sub_140369E60
    // @PTN E:L(F13,0)@[?:0x8] {conf=high} -> A(F1,0)
    // @PTN G:G(0x140369E60) -> F(F13)
0x145FD2CF9: mov     rax, [rsp+188h+arg_0]
0x145FD2D01: lea     rcx, off_148AE9D70
0x145FD2D08: mov     [rax], rcx
    // @PTN G:G(0x148AE9D70) -> F(F13)
    // @PTN G:G(0x148AE9D70) -> F(F13)
0x145FD2D0B: mov     rax, [rsp+188h+arg_0]
0x145FD2D13: vmovss  xmm0, cs:Y
0x145FD2D1B: vmovss  dword ptr [rax+8], xmm0
0x145FD2D20: mov     rax, [rsp+188h+arg_0]
0x145FD2D28: add     rax, 10h
0x145FD2D2C: mov     rcx, rax
0x145FD2D2F: call    SXYZCurvesWithMaxValuesModifer__Init
    // @PTN E:L(F13,0)@[0x10:0x8] {conf=high} -> A(F17,0)
    // @PTN G:G(0x145FD5A10) -> F(F13)
0x145FD2D34: mov     rax, [rsp+188h+arg_0]
0x145FD2D3C: add     rax, 70h ; 'p'
0x145FD2D40: mov     rcx, rax
0x145FD2D43: call    SXYZCurvesWithMaxValuesModifer__Init
    // @PTN E:L(F13,0)@[0x70:0x8] {conf=high} -> A(F17,0)
    // @PTN G:G(0x145FD5A10) -> F(F13)
0x145FD2D48: mov     rax, [rsp+188h+arg_0]
0x145FD2D50: vmovss  xmm0, cs:Y
0x145FD2D58: vmovss  dword ptr [rax+0D0h], xmm0
0x145FD2D60: mov     rax, [rsp+188h+arg_0]
0x145FD2D68: vmovss  xmm0, cs:Y
0x145FD2D70: vmovss  dword ptr [rax+0D4h], xmm0
0x145FD2D78: mov     rax, [rsp+188h+arg_0]
0x145FD2D80: add     rax, 0D8h
0x145FD2D86: mov     rcx, rax
0x145FD2D89: call    SActorProceduralHandsRecoilCurveDecayModifiersDef__Init
    // @PTN E:L(F13,0)@[0xD8:0x8] {conf=high} -> A(F12,0)
    // @PTN G:G(0x145FD2BD0) -> F(F13)
0x145FD2D8E: mov     rax, [rsp+188h+arg_0]
0x145FD2D96: add     rax, 128h
0x145FD2D9C: mov     rcx, rax
0x145FD2D9F: call    SActorProceduralHandsRecoilCurveDecayModifiersDef__Init
    // @PTN E:L(F13,0)@[0x128:0x8] {conf=high} -> A(F12,0)
    // @PTN G:G(0x145FD2BD0) -> F(F13)
0x145FD2DA4: lea     rcx, [rsp+188h+var_C8]
0x145FD2DAC: call    SXYZCurvesWithMaxValuesModifer__Init
    // @PTN E:L(F13,8)@[?:0x8] {conf=high} -> A(F17,0)
    // @PTN G:G(0x145FD5A10) -> F(F13)
    // @PTN G:G(0x145FD5A10) -> F(F13)
0x145FD2DB1: mov     rcx, [rsp+188h+arg_0]
0x145FD2DB9: add     rcx, 10h
0x145FD2DBD: mov     rdx, rax
0x145FD2DC0: call    SXYZCurvesWithMaxValuesModifer__CopyParams
    // @PTN E:L(F13,0)@[0x10:0x8] {conf=high} -> A(F9,0)
    // @PTN E:L(F13,1)@[?:0x8] {conf=high} -> A(F9,1)
    // @PTN G:G(0x1431833F0) -> F(F13)
0x145FD2DC5: lea     rcx, [rsp+188h+var_C8]
0x145FD2DCD: call    sub_14275A5F0
    // @PTN E:L(F13,8)@[?:0x8] {conf=high} -> A(F4,0)
    // @PTN G:G(0x14275A5F0) -> F(F13)
0x145FD2DD2: lea     rcx, [rsp+188h+var_68]
0x145FD2DDA: call    SXYZCurvesWithMaxValuesModifer__Init
    // @PTN E:L(F13,9)@[?:0x8] {conf=high} -> A(F17,0)
    // @PTN G:G(0x145FD5A10) -> F(F13)
    // @PTN G:G(0x145FD5A10) -> F(F13)
0x145FD2DDF: mov     rcx, [rsp+188h+arg_0]
0x145FD2DE7: add     rcx, 70h ; 'p'
0x145FD2DEB: mov     rdx, rax
0x145FD2DEE: call    SXYZCurvesWithMaxValuesModifer__CopyParams
    // @PTN E:L(F13,0)@[0x70:0x8] {conf=high} -> A(F9,0)
    // @PTN E:L(F13,2)@[?:0x8] {conf=high} -> A(F9,1)
    // @PTN G:G(0x1431833F0) -> F(F13)
0x145FD2DF3: lea     rcx, [rsp+188h+var_68]
0x145FD2DFB: call    sub_14275A5F0
    // @PTN E:L(F13,9)@[?:0x8] {conf=high} -> A(F4,0)
    // @PTN G:G(0x14275A5F0) -> F(F13)
0x145FD2E00: lea     rcx, [rsp+188h+var_168]
0x145FD2E05: call    SActorProceduralHandsRecoilCurveDecayModifiersDef__Init
    // @PTN E:L(F13,6)@[?:0x8] {conf=high} -> A(F12,0)
    // @PTN G:G(0x145FD2BD0) -> F(F13)
    // @PTN G:G(0x145FD2BD0) -> F(F13)
0x145FD2E0A: mov     rcx, [rsp+188h+arg_0]
0x145FD2E12: add     rcx, 0D8h
0x145FD2E19: mov     rdx, rax
0x145FD2E1C: call    SActorProceduralHandsRecoilCurveDecayModifiersDef__CopyParams
    // @PTN E:L(F13,0)@[0xD8:0x8] {conf=high} -> A(F8,0)
    // @PTN E:L(F13,3)@[?:0x8] {conf=high} -> A(F8,1)
    // @PTN G:G(0x143181DF0) -> F(F13)
0x145FD2E21: lea     rcx, [rsp+188h+var_168]
0x145FD2E26: call    sub_14037BF20
    // @PTN E:L(F13,6)@[?:0x8] {conf=high} -> A(F2,0)
    // @PTN G:G(0x14037BF20) -> F(F13)
0x145FD2E2B: lea     rcx, [rsp+188h+var_118]
0x145FD2E30: call    SActorProceduralHandsRecoilCurveDecayModifiersDef__Init
    // @PTN E:L(F13,7)@[?:0x8] {conf=high} -> A(F12,0)
    // @PTN G:G(0x145FD2BD0) -> F(F13)
    // @PTN G:G(0x145FD2BD0) -> F(F13)
0x145FD2E35: mov     rcx, [rsp+188h+arg_0]
0x145FD2E3D: add     rcx, 128h
0x145FD2E44: mov     rdx, rax
0x145FD2E47: call    SActorProceduralHandsRecoilCurveDecayModifiersDef__CopyParams
    // @PTN E:L(F13,0)@[0x128:0x8] {conf=high} -> A(F8,0)
    // @PTN E:L(F13,4)@[?:0x8] {conf=high} -> A(F8,1)
    // @PTN G:G(0x143181DF0) -> F(F13)
0x145FD2E4C: lea     rcx, [rsp+188h+var_118]
0x145FD2E51: call    sub_14037BF20
    // @PTN E:L(F13,7)@[?:0x8] {conf=high} -> A(F2,0)
    // @PTN G:G(0x14037BF20) -> F(F13)
0x145FD2E56: mov     rax, [rsp+188h+arg_0]
0x145FD2E5E: add     rsp, 188h
0x145FD2E65: retn
// --- End Function: SActorProceduralHandsRecoilCurveModifiersDef::Init (0x145FD2CE0) ---

